# -*- coding: utf-8 -*-
"""서남·서북권 자치구 데이터 (강서·양천·마포·서대문·은평)."""

GU = [
    {
        "slug": "gangseo-gu",
        "name": "강서구",
        "priority": 1,
        "trait": "마곡 첨단 업무지구와 김포공항 배후 주거가 어우러진",
        "lead": "강서구는 마곡지구의 연구·업무 단지가 빠르게 성장하면서 오피스텔과 "
                "비즈니스호텔 수요가 늘어난 자치구입니다. 화곡동·등촌동의 오래된 주거지와 "
                "김포공항·가양 일대가 함께 있어 권역별 방문 동선이 뚜렷하게 나뉩니다.",
        "stations": ["마곡역", "발산역", "화곡역", "가양역", "김포공항역", "까치산역"],
        "life_areas": [],
        "dongs": [
            {"slug": "magok-dong", "name": "마곡동", "priority": 1,
             "character": "마곡 첨단산업단지와 연구소·기업 사옥이 밀집한 신흥 업무 중심지",
             "landmarks": ["서울식물원", "LG사이언스파크", "마곡나루역"],
             "nearby_stations": ["마곡역", "발산역", "가양역"],
             "nearby_dongs": ["발산동", "가양동", "공항동"],
             "life_area": ""},
            {"slug": "balsan-dong", "name": "발산동", "priority": 1,
             "character": "이대서울병원과 발산역 상권을 낀 의료·생활 권역",
             "landmarks": ["이대서울병원", "발산역", "강서구청"],
             "nearby_stations": ["발산역", "마곡역", "화곡역"],
             "nearby_dongs": ["마곡동", "화곡동", "공항동"],
             "life_area": ""},
            {"slug": "hwagok-dong", "name": "화곡동", "priority": 1,
             "character": "다세대·다가구가 밀집한 서울 최대급 주거 밀집지",
             "landmarks": ["화곡역", "강서구청", "까치산시장"],
             "nearby_stations": ["화곡역", "까치산역", "발산역"],
             "nearby_dongs": ["발산동", "등촌동", "염창동"],
             "life_area": ""},
            {"slug": "deungchon-dong", "name": "등촌동", "priority": 1,
             "character": "아파트 단지와 NC백화점 상권이 형성된 주거·상업 혼합지",
             "landmarks": ["등촌역", "강서보건소", "NC백화점 강서점"],
             "nearby_stations": ["등촌역", "염창역", "가양역"],
             "nearby_dongs": ["염창동", "화곡동", "가양동"],
             "life_area": ""},
            {"slug": "gayang-dong", "name": "가양동", "priority": 1,
             "character": "대단지 아파트와 한강변 공원이 자리한 정주 권역",
             "landmarks": ["가양역", "허준박물관", "한강 가양지구"],
             "nearby_stations": ["가양역", "증미역", "등촌역"],
             "nearby_dongs": ["등촌동", "염창동", "마곡동"],
             "life_area": ""},
            {"slug": "yeomchang-dong", "name": "염창동", "priority": 2,
             "character": "한강변 아파트와 9호선 역세권이 결합된 주거지",
             "landmarks": ["염창역", "증미역", "한강 안양천 합류부"],
             "nearby_stations": ["염창역", "등촌역", "가양역"],
             "nearby_dongs": ["등촌동", "가양동", "화곡동"],
             "life_area": ""},
            {"slug": "gonghang-dong", "name": "공항동", "priority": 2,
             "character": "김포공항을 끼고 항공 관련 시설과 주거가 섞인 권역",
             "landmarks": ["김포공항", "롯데몰 김포공항", "공항시장"],
             "nearby_stations": ["김포공항역", "발산역", "마곡역"],
             "nearby_dongs": ["방화동", "발산동", "마곡동"],
             "life_area": ""},
            {"slug": "banghwa-dong", "name": "방화동", "priority": 2,
             "character": "5호선 종점부와 공항 배후 아파트가 자리한 외곽 주거지",
             "landmarks": ["방화역", "개화산", "강서한강공원"],
             "nearby_stations": ["김포공항역", "마곡역", "발산역"],
             "nearby_dongs": ["공항동", "마곡동", "발산동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "yangcheon-gu",
        "name": "양천구",
        "priority": 1,
        "trait": "목동 학원가와 대단지 아파트가 중심을 이루는",
        "lead": "양천구는 목동 신시가지 아파트와 학원가를 중심으로 정주 인구가 많은 "
                "주거 중심 자치구입니다. 목동·오목교 상권과 신정·신월의 주거지가 "
                "권역을 이뤄 시간대에 따른 방문 수요가 안정적인 편입니다.",
        "stations": ["목동역", "오목교역", "신정네거리역", "양천구청역"],
        "life_areas": ["목동·양천"],
        "dongs": [
            {"slug": "mok-dong", "name": "목동", "priority": 1,
             "character": "목동 신시가지 아파트와 학원가가 밀집한 교육·주거 중심지",
             "landmarks": ["목동운동장", "현대백화점 목동점", "목동 학원가"],
             "nearby_stations": ["목동역", "오목교역", "양천구청역"],
             "nearby_dongs": ["신정동", "신월동", "염창동"],
             "life_area": "목동·양천"},
            {"slug": "sinjeong-dong", "name": "신정동", "priority": 1,
             "character": "신정네거리 상권과 대단지 아파트가 결합된 주거 권역",
             "landmarks": ["신정네거리역", "서서울호수공원", "양천구청"],
             "nearby_stations": ["신정네거리역", "양천구청역", "오목교역"],
             "nearby_dongs": ["목동", "신월동", "신정동"],
             "life_area": "목동·양천"},
            {"slug": "sinwol-dong", "name": "신월동", "priority": 1,
             "character": "다세대 주거가 밀집하고 까치산역 상권을 낀 정주지",
             "landmarks": ["까치산역", "신월동성당", "곰달래로"],
             "nearby_stations": ["까치산역", "신정네거리역", "화곡역"],
             "nearby_dongs": ["신정동", "목동", "화곡동"],
             "life_area": "목동·양천"},
        ],
    },
    {
        "slug": "mapo-gu",
        "name": "마포구",
        "priority": 1,
        "trait": "홍대 상권과 공덕 업무지구가 양 축을 이루는",
        "lead": "마포구는 홍대·합정·연남의 활발한 상권과 공덕의 업무·교통 결절점이 "
                "양 축을 이루는 자치구입니다. 호텔과 게스트하우스, 오피스텔이 많아 "
                "방문형 관리 동선이 비교적 촘촘하게 형성되어 있습니다.",
        "stations": ["홍대입구역", "합정역", "공덕역", "망원역", "디지털미디어시티역"],
        "life_areas": ["홍대·합정", "공덕·마포"],
        "dongs": [
            {"slug": "seogyo-dong", "name": "서교동", "priority": 1,
             "character": "홍대 클럽·라이브 상권의 중심을 이루는 번화 권역",
             "landmarks": ["홍대입구역", "홍대 걷고싶은거리", "경의선숲길"],
             "nearby_stations": ["홍대입구역", "합정역", "상수역"],
             "nearby_dongs": ["합정동", "연남동", "상수동"],
             "life_area": "홍대·합정"},
            {"slug": "hapjeong-dong", "name": "합정동", "priority": 1,
             "character": "메세나폴리스와 한강변 카페거리가 모인 상업·주거 복합지",
             "landmarks": ["메세나폴리스", "합정역", "절두산성지"],
             "nearby_stations": ["합정역", "홍대입구역", "상수역"],
             "nearby_dongs": ["서교동", "망원동", "상수동"],
             "life_area": "홍대·합정"},
            {"slug": "yeonnam-dong", "name": "연남동", "priority": 1,
             "character": "연트럴파크를 따라 카페·맛집이 늘어선 감성 상권",
             "landmarks": ["경의선숲길 연남동구간", "연남동 카페거리", "홍대입구역"],
             "nearby_stations": ["홍대입구역", "디지털미디어시티역", "합정역"],
             "nearby_dongs": ["서교동", "합정동", "성산동"],
             "life_area": "홍대·합정"},
            {"slug": "mangwon-dong", "name": "망원동", "priority": 1,
             "character": "망원시장과 한강공원을 낀 생활밀착형 주거·상권",
             "landmarks": ["망원시장", "망원한강공원", "망원역"],
             "nearby_stations": ["망원역", "합정역", "홍대입구역"],
             "nearby_dongs": ["합정동", "성산동", "서교동"],
             "life_area": "홍대·합정"},
            {"slug": "gongdeok-dong", "name": "공덕동", "priority": 1,
             "character": "공덕역 4개 노선 환승과 오피스·호텔이 밀집한 업무 결절지",
             "landmarks": ["공덕역", "마포대로", "효성해링턴스퀘어"],
             "nearby_stations": ["공덕역", "디지털미디어시티역", "합정역"],
             "nearby_dongs": ["아현동", "상수동", "서교동"],
             "life_area": "공덕·마포"},
            {"slug": "sangsu-dong", "name": "상수동", "priority": 2,
             "character": "홍대 인근 골목 카페와 한강변이 어우러진 주거·상권",
             "landmarks": ["상수역", "당인리발전소 부지", "홍대 인근 골목상권"],
             "nearby_stations": ["상수역", "합정역", "홍대입구역"],
             "nearby_dongs": ["서교동", "합정동", "공덕동"],
             "life_area": "홍대·합정"},
            {"slug": "sangam-dong", "name": "상암동", "priority": 2,
             "character": "DMC 방송·미디어 단지와 월드컵공원이 자리한 업무·여가 권역",
             "landmarks": ["디지털미디어시티", "월드컵경기장", "하늘공원"],
             "nearby_stations": ["디지털미디어시티역", "망원역", "홍대입구역"],
             "nearby_dongs": ["성산동", "망원동", "연남동"],
             "life_area": ""},
            {"slug": "seongsan-dong", "name": "성산동", "priority": 2,
             "character": "성미산마을과 월드컵 배후 아파트가 자리한 주거지",
             "landmarks": ["성미산", "월드컵공원", "마포구청"],
             "nearby_stations": ["디지털미디어시티역", "망원역", "합정역"],
             "nearby_dongs": ["상암동", "망원동", "연남동"],
             "life_area": ""},
            {"slug": "ahyeon-dong", "name": "아현동", "priority": 2,
             "character": "웨딩거리와 재개발 아파트가 섞인 도심 인접 주거지",
             "landmarks": ["아현역", "아현웨딩거리", "마포래미안푸르지오"],
             "nearby_stations": ["공덕역", "홍대입구역", "합정역"],
             "nearby_dongs": ["공덕동", "서교동", "상수동"],
             "life_area": "공덕·마포"},
        ],
    },
    {
        "slug": "seodaemun-gu",
        "name": "서대문구",
        "priority": 1,
        "trait": "신촌 대학가와 안산 자락 주거지가 공존하는",
        "lead": "서대문구는 신촌·이대 대학가 상권과 연희·홍은의 조용한 주거지가 "
                "공존하는 자치구입니다. 안산과 인왕산을 끼고 주택가가 넓게 펼쳐져 "
                "권역별로 생활 분위기가 뚜렷하게 구분됩니다.",
        "stations": ["신촌역", "이대역", "홍제역", "가좌역"],
        "life_areas": [],
        "dongs": [
            {"slug": "sinchon-dong", "name": "신촌동", "priority": 2,
             "character": "연세대 앞 상권과 유흥·먹자거리가 밀집한 대학가 중심지",
             "landmarks": ["연세대학교", "신촌역", "현대백화점 신촌점"],
             "nearby_stations": ["신촌역", "이대역", "홍대입구역"],
             "nearby_dongs": ["연희동", "남가좌동", "북아현동"],
             "life_area": ""},
            {"slug": "yeonhui-dong", "name": "연희동", "priority": 2,
             "character": "단독주택가와 골목 맛집·카페가 어우러진 정주 권역",
             "landmarks": ["연희동 맛집골목", "사러가시장", "안산자락길"],
             "nearby_stations": ["신촌역", "가좌역", "홍제역"],
             "nearby_dongs": ["신촌동", "홍제동", "남가좌동"],
             "life_area": ""},
            {"slug": "hongje-dong", "name": "홍제동", "priority": 2,
             "character": "인왕산 자락 아파트와 홍제역 상권이 결합된 주거지",
             "landmarks": ["홍제역", "인왕산", "홍제천"],
             "nearby_stations": ["홍제역", "신촌역", "가좌역"],
             "nearby_dongs": ["홍은동", "연희동", "남가좌동"],
             "life_area": ""},
            {"slug": "hongeun-dong", "name": "홍은동", "priority": 2,
             "character": "북한산·안산 자락의 대단지 아파트가 자리한 외곽 주거지",
             "landmarks": ["홍은사거리", "북한산 자락", "포방터시장"],
             "nearby_stations": ["홍제역", "신촌역", "가좌역"],
             "nearby_dongs": ["홍제동", "연희동", "북가좌동"],
             "life_area": ""},
            {"slug": "namgajwa-dong", "name": "남가좌동", "priority": 2,
             "character": "가재울뉴타운 신축 아파트가 들어선 정비 주거 권역",
             "landmarks": ["가재울뉴타운", "가좌역", "모래내시장"],
             "nearby_stations": ["가좌역", "신촌역", "디지털미디어시티역"],
             "nearby_dongs": ["북가좌동", "연희동", "신촌동"],
             "life_area": ""},
            {"slug": "bukgajwa-dong", "name": "북가좌동", "priority": 2,
             "character": "주택가와 가재울 인근 아파트가 섞인 생활 주거지",
             "landmarks": ["불광천", "북가좌삼거리", "가재울뉴타운"],
             "nearby_stations": ["가좌역", "디지털미디어시티역", "홍제역"],
             "nearby_dongs": ["남가좌동", "홍은동", "연희동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "eunpyeong-gu",
        "name": "은평구",
        "priority": 1,
        "trait": "연신내 상권과 북한산 자락 주거단지가 이어지는",
        "lead": "은평구는 연신내·불광 상권을 중심으로 응암·역촌의 주거지와 진관동 "
                "은평뉴타운이 이어지는 자치구입니다. 북한산을 배경으로 한 대단지 "
                "주거가 많아 정주형 생활 수요가 안정적으로 형성되어 있습니다.",
        "stations": ["연신내역", "불광역", "응암역", "구파발역"],
        "life_areas": ["연신내·은평"],
        "dongs": [
            {"slug": "bulgwang-dong", "name": "불광동", "priority": 1,
             "character": "불광역·연신내 상권을 낀 은평구 교통·생활 중심지",
             "landmarks": ["불광역", "연신내역", "북한산 둘레길 입구"],
             "nearby_stations": ["불광역", "연신내역", "녹번역"],
             "nearby_dongs": ["녹번동", "갈현동", "대조동"],
             "life_area": "연신내·은평"},
            {"slug": "eungam-dong", "name": "응암동", "priority": 1,
             "character": "다세대 주거와 응암역 상권이 밀집한 정주 권역",
             "landmarks": ["응암역", "응암오거리", "백련산"],
             "nearby_stations": ["응암역", "새절역", "역촌역"],
             "nearby_dongs": ["역촌동", "녹번동", "신사동"],
             "life_area": "연신내·은평"},
            {"slug": "yeokchon-dong", "name": "역촌동", "priority": 1,
             "character": "주택가와 역촌역 상권이 어우러진 생활밀착형 주거지",
             "landmarks": ["역촌역", "역촌중앙시장", "백련산 자락"],
             "nearby_stations": ["역촌역", "응암역", "불광역"],
             "nearby_dongs": ["응암동", "대조동", "갈현동"],
             "life_area": "연신내·은평"},
            {"slug": "jingwan-dong", "name": "진관동", "priority": 1,
             "character": "은평뉴타운 대단지와 한옥마을이 자리한 신흥 주거 권역",
             "landmarks": ["은평뉴타운", "은평한옥마을", "구파발역"],
             "nearby_stations": ["구파발역", "연신내역", "불광역"],
             "nearby_dongs": ["구산동", "갈현동", "불광동"],
             "life_area": "연신내·은평"},
            {"slug": "nokbeon-dong", "name": "녹번동", "priority": 2,
             "character": "녹번역 인근 재개발 아파트와 주택가가 섞인 주거지",
             "landmarks": ["녹번역", "백련산 힐스테이트", "산골고개"],
             "nearby_stations": ["녹번역", "불광역", "응암역"],
             "nearby_dongs": ["불광동", "응암동", "갈현동"],
             "life_area": "연신내·은평"},
            {"slug": "galhyeon-dong", "name": "갈현동", "priority": 2,
             "character": "연신내 배후 주택가와 갈현시장 상권이 자리한 정주지",
             "landmarks": ["갈현시장", "연신내역", "선림사"],
             "nearby_stations": ["연신내역", "구파발역", "불광역"],
             "nearby_dongs": ["구산동", "대조동", "진관동"],
             "life_area": "연신내·은평"},
            {"slug": "gusan-dong", "name": "구산동", "priority": 2,
             "character": "구산역 인근 주택가와 봉산 자락이 어우러진 주거 권역",
             "landmarks": ["구산역", "봉산 편백나무숲", "예일여고"],
             "nearby_stations": ["구산역", "연신내역", "응암역"],
             "nearby_dongs": ["갈현동", "역촌동", "대조동"],
             "life_area": "연신내·은평"},
            {"slug": "daejo-dong", "name": "대조동", "priority": 2,
             "character": "연신내 상권 배후의 다세대 주거 밀집지",
             "landmarks": ["연신내역", "연서시장", "대조동 주민센터"],
             "nearby_stations": ["연신내역", "불광역", "구파발역"],
             "nearby_dongs": ["불광동", "갈현동", "역촌동"],
             "life_area": "연신내·은평"},
        ],
    },
]
