# -*- coding: utf-8 -*-
"""강남구 데이터 (스키마 예시 겸 1차 색인용)."""

GU = [
    {
        "slug": "gangnam-gu",
        "name": "강남구",
        "priority": 1,
        "trait": "테헤란로 업무지구와 고급 주거가 공존하는",
        "lead": "강남구는 역삼·삼성을 잇는 테헤란로 업무지구와 청담·압구정의 고급 "
                "주거·상권이 함께 있어, 시간대와 위치에 따라 방문 수요가 크게 갈리는 "
                "자치구입니다. 오피스텔과 비즈니스호텔이 많아 방문형 관리 동선이 비교적 "
                "명확한 편입니다.",
        "stations": ["강남역", "역삼역", "선릉역", "삼성역", "청담역", "압구정역"],
        "life_areas": ["강남·역삼", "삼성·선릉", "청담·압구정"],
        "dongs": [
            {"slug": "yeoksam-dong", "name": "역삼동", "priority": 1,
             "character": "테헤란로 오피스 밀집과 오피스텔·비즈니스호텔이 많은 업무 중심지",
             "landmarks": ["테헤란로", "강남파이낸스센터", "역삼역 일대"],
             "nearby_stations": ["강남역", "역삼역", "선릉역"],
             "nearby_dongs": ["논현동", "삼성동", "대치동"],
             "life_area": "강남·역삼"},
            {"slug": "nonhyeon-dong", "name": "논현동", "priority": 1,
             "character": "가구거리와 먹자골목, 오피스텔이 섞인 상업·주거 혼합지",
             "landmarks": ["논현역", "학동사거리", "영동시장"],
             "nearby_stations": ["논현역", "강남역", "학동역"],
             "nearby_dongs": ["역삼동", "신사동", "삼성동"],
             "life_area": "강남·역삼"},
            {"slug": "samseong-dong", "name": "삼성동", "priority": 1,
             "character": "코엑스·무역센터 중심의 업무·전시 권역",
             "landmarks": ["코엑스", "무역센터", "봉은사"],
             "nearby_stations": ["삼성역", "선릉역", "봉은사역"],
             "nearby_dongs": ["대치동", "역삼동", "청담동"],
             "life_area": "삼성·선릉"},
            {"slug": "cheongdam-dong", "name": "청담동", "priority": 1,
             "character": "명품거리와 갤러리, 고급 주거가 모인 프리미엄 권역",
             "landmarks": ["청담명품거리", "갤러리아", "청담역"],
             "nearby_stations": ["청담역", "압구정로데오역", "삼성역"],
             "nearby_dongs": ["압구정동", "삼성동", "신사동"],
             "life_area": "청담·압구정"},
            {"slug": "apgujeong-dong", "name": "압구정동", "priority": 1,
             "character": "로데오거리와 고급 아파트 단지가 자리한 주거·상권 복합지",
             "landmarks": ["압구정로데오", "현대백화점", "한강시민공원"],
             "nearby_stations": ["압구정역", "압구정로데오역", "신사역"],
             "nearby_dongs": ["청담동", "신사동", "논현동"],
             "life_area": "청담·압구정"},
            {"slug": "daechi-dong", "name": "대치동", "priority": 1,
             "character": "학원가와 대단지 아파트가 밀집한 주거·교육 중심지",
             "landmarks": ["대치동 학원가", "은마아파트", "한티역"],
             "nearby_stations": ["대치역", "한티역", "선릉역"],
             "nearby_dongs": ["삼성동", "도곡동", "역삼동"],
             "life_area": "삼성·선릉"},
            {"slug": "sinsa-dong", "name": "신사동", "priority": 2,
             "character": "가로수길 상권과 성형외과 거리가 형성된 패션·상업지",
             "landmarks": ["가로수길", "신사역", "도산공원"],
             "nearby_stations": ["신사역", "압구정역", "논현역"],
             "nearby_dongs": ["논현동", "압구정동", "청담동"],
             "life_area": "청담·압구정"},
            {"slug": "dogok-dong", "name": "도곡동", "priority": 2,
             "character": "타워팰리스와 고급 주거가 자리한 정주 권역",
             "landmarks": ["타워팰리스", "매봉산", "도곡역"],
             "nearby_stations": ["도곡역", "한티역", "양재역"],
             "nearby_dongs": ["대치동", "역삼동", "개포동"],
             "life_area": "삼성·선릉"},
            {"slug": "suseo-dong", "name": "수서동", "priority": 2,
             "character": "수서역 SRT·복합환승과 신규 개발이 진행되는 권역",
             "landmarks": ["수서역", "SRT", "광평로"],
             "nearby_stations": ["수서역", "대모산입구역", "일원역"],
             "nearby_dongs": ["일원동", "세곡동", "개포동"],
             "life_area": "삼성·선릉"},
        ],
    }
]
