# -*- coding: utf-8 -*-
"""서초·송파·강동·광진·성동구 데이터."""

GU = [
    {
        "slug": "seocho-gu",
        "name": "서초구",
        "priority": 1,
        "trait": "법조타운과 고속터미널, 양재 R&D가 어우러진",
        "lead": "서초구는 교대·서초동 법조타운과 강남대로 업무지구, 고속터미널 상권이 "
                "축을 이루는 자치구입니다. 반포·방배의 대단지 주거와 양재 연구개발 권역이 "
                "함께 있어 평일 업무 동선과 주말 주거 동선이 뚜렷하게 갈립니다.",
        "stations": ["교대역", "고속터미널역", "양재역", "사당역", "방배역", "잠원역"],
        "life_areas": ["강남·역삼"],
        "dongs": [
            {"slug": "seocho-dong", "name": "서초동", "priority": 1,
             "character": "대법원·대검찰청과 예술의전당이 자리한 법조·문화 중심지",
             "landmarks": ["대법원", "예술의전당", "서울중앙지방법원"],
             "nearby_stations": ["교대역", "양재역", "강남역"],
             "nearby_dongs": ["반포동", "방배동", "양재동"],
             "life_area": "강남·역삼"},
            {"slug": "banpo-dong", "name": "반포동", "priority": 1,
             "character": "고속터미널 상권과 반포 한강 대단지 아파트가 모인 주거·상업 복합지",
             "landmarks": ["고속터미널", "신세계백화점 강남점", "반포한강공원"],
             "nearby_stations": ["고속터미널역", "잠원역", "교대역"],
             "nearby_dongs": ["잠원동", "서초동", "방배동"],
             "life_area": ""},
            {"slug": "bangbae-dong", "name": "방배동", "priority": 1,
             "character": "카페골목과 빌라·아파트가 섞인 조용한 주거·상권 지역",
             "landmarks": ["방배역", "서리풀공원", "방배카페골목"],
             "nearby_stations": ["방배역", "사당역", "내방역"],
             "nearby_dongs": ["서초동", "반포동", "사당동"],
             "life_area": ""},
            {"slug": "yangjae-dong", "name": "양재동", "priority": 1,
             "character": "양재 R&D 단지와 화훼공판장, 양재시민의숲이 있는 연구·물류 권역",
             "landmarks": ["양재시민의숲", "aT센터", "양재화훼공판장"],
             "nearby_stations": ["양재역", "양재시민의숲역", "매봉역"],
             "nearby_dongs": ["서초동", "우면동", "내곡동"],
             "life_area": ""},
            {"slug": "jamwon-dong", "name": "잠원동", "priority": 2,
             "character": "반포 인접 한강변 아파트가 밀집한 정주 권역",
             "landmarks": ["잠원한강공원", "잠원역", "신반포로"],
             "nearby_stations": ["잠원역", "고속터미널역", "신사역"],
             "nearby_dongs": ["반포동", "서초동", "압구정동"],
             "life_area": ""},
            {"slug": "naegok-dong", "name": "내곡동", "priority": 2,
             "character": "헌인마을과 보금자리지구, 자연녹지가 넓은 외곽 주거지",
             "landmarks": ["헌릉", "내곡지구", "구룡산"],
             "nearby_stations": ["양재역", "청계산입구역", "양재시민의숲역"],
             "nearby_dongs": ["양재동", "세곡동", "우면동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "songpa-gu",
        "name": "송파구",
        "priority": 1,
        "trait": "잠실 관광·상업지구와 문정 법조·업무벨트를 아우르는",
        "lead": "송파구는 롯데월드타워와 잠실역을 중심으로 한 대규모 상업·관광지구와 "
                "문정·가락의 법조타운·도매시장 권역이 함께 있는 자치구입니다. 비즈니스호텔과 "
                "오피스텔, 대단지 아파트가 고루 분포해 시간대별 방문 수요가 다양합니다.",
        "stations": ["잠실역", "석촌역", "가락시장역", "문정역", "장지역"],
        "life_areas": ["잠실·송파", "문정·가락"],
        "dongs": [
            {"slug": "jamsil-dong", "name": "잠실동", "priority": 1,
             "character": "롯데월드타워·석촌호수 중심의 관광·상업·고층주거 복합지",
             "landmarks": ["롯데월드타워", "석촌호수", "잠실종합운동장"],
             "nearby_stations": ["잠실역", "석촌역", "잠실나루역"],
             "nearby_dongs": ["석촌동", "방이동", "신천동"],
             "life_area": "잠실·송파"},
            {"slug": "bangi-dong", "name": "방이동", "priority": 1,
             "character": "올림픽공원과 먹자골목·숙박이 어우러진 상권·주거 혼합지",
             "landmarks": ["올림픽공원", "방이먹자골목", "한성백제역"],
             "nearby_stations": ["잠실역", "방이역", "올림픽공원역"],
             "nearby_dongs": ["오금동", "가락동", "잠실동"],
             "life_area": "잠실·송파"},
            {"slug": "seokchon-dong", "name": "석촌동", "priority": 1,
             "character": "석촌호수 인접 주거지와 백제 고분군이 있는 정주 권역",
             "landmarks": ["석촌호수", "석촌동 고분군", "석촌역"],
             "nearby_stations": ["석촌역", "송파역", "잠실역"],
             "nearby_dongs": ["잠실동", "송파동", "가락동"],
             "life_area": "잠실·송파"},
            {"slug": "garak-dong", "name": "가락동", "priority": 1,
             "character": "가락농수산물도매시장 중심의 유통·도매와 주거 혼합지",
             "landmarks": ["가락시장", "헬리오시티", "가락시장역"],
             "nearby_stations": ["가락시장역", "송파역", "문정역"],
             "nearby_dongs": ["문정동", "석촌동", "오금동"],
             "life_area": "문정·가락"},
            {"slug": "munjeong-dong", "name": "문정동", "priority": 1,
             "character": "동부지방법원·검찰청과 법조단지, 로데오 아웃렛이 모인 업무·상업지",
             "landmarks": ["서울동부지방법원", "문정법조타운", "문정로데오거리"],
             "nearby_stations": ["문정역", "가락시장역", "장지역"],
             "nearby_dongs": ["가락동", "장지동", "오금동"],
             "life_area": "문정·가락"},
            {"slug": "ogeum-dong", "name": "오금동", "priority": 2,
             "character": "아파트 단지와 근린상권이 자리한 조용한 주거지",
             "landmarks": ["오금역", "오금공원", "성내천"],
             "nearby_stations": ["오금역", "방이역", "가락시장역"],
             "nearby_dongs": ["방이동", "가락동", "거여동"],
             "life_area": ""},
            {"slug": "songpa-dong", "name": "송파동", "priority": 2,
             "character": "송리단길 상권과 주택가가 어우러진 주거·먹자 권역",
             "landmarks": ["송리단길", "송파역", "삼전동 일대"],
             "nearby_stations": ["송파역", "석촌역", "가락시장역"],
             "nearby_dongs": ["석촌동", "가락동", "잠실동"],
             "life_area": "잠실·송파"},
            {"slug": "jangji-dong", "name": "장지동", "priority": 2,
             "character": "가든파이브와 위례 인접 신규 주거가 형성된 권역",
             "landmarks": ["가든파이브", "장지역", "탄천"],
             "nearby_stations": ["장지역", "문정역", "복정역"],
             "nearby_dongs": ["문정동", "가락동", "거여동"],
             "life_area": "문정·가락"},
        ],
    },
    {
        "slug": "gangdong-gu",
        "name": "강동구",
        "priority": 1,
        "trait": "천호 상권과 고덕·둔촌 재건축 대단지가 확장되는",
        "lead": "강동구는 천호역 일대 상업·교통 중심지와 고덕·둔촌의 대규모 재건축 "
                "주거단지가 빠르게 늘고 있는 자치구입니다. 한강과 암사 선사유적을 낀 "
                "정주형 생활권이 넓어 방문 수요는 주거 지역에 비교적 고르게 분포합니다.",
        "stations": ["천호역", "강동역", "암사역", "길동역", "둔촌동역", "고덕역"],
        "life_areas": [],
        "dongs": [
            {"slug": "cheonho-dong", "name": "천호동", "priority": 2,
             "character": "백화점·로데오 상권과 환승역이 결합한 강동의 상업 중심지",
             "landmarks": ["현대백화점 천호점", "천호역", "천호로데오거리"],
             "nearby_stations": ["천호역", "강동역", "암사역"],
             "nearby_dongs": ["성내동", "암사동", "강동역 일대"],
             "life_area": ""},
            {"slug": "seongnae-dong", "name": "성내동", "priority": 2,
             "character": "강동구청과 먹자골목·오피스텔이 모인 행정·상권 지역",
             "landmarks": ["강동구청", "강동역", "성내천"],
             "nearby_stations": ["강동역", "천호역", "둔촌동역"],
             "nearby_dongs": ["천호동", "둔촌동", "길동"],
             "life_area": ""},
            {"slug": "amsa-dong", "name": "암사동", "priority": 2,
             "character": "암사동 선사유적지와 한강변 아파트가 있는 정주 권역",
             "landmarks": ["암사동 선사유적지", "암사역", "광나루한강공원"],
             "nearby_stations": ["암사역", "천호역", "강동역"],
             "nearby_dongs": ["천호동", "고덕동", "성내동"],
             "life_area": ""},
            {"slug": "gil-dong", "name": "길동", "priority": 2,
             "character": "길동사거리 상권과 빌라·아파트가 섞인 주거지",
             "landmarks": ["길동역", "길동생태공원", "강동성심병원"],
             "nearby_stations": ["길동역", "굽은다리역", "둔촌동역"],
             "nearby_dongs": ["성내동", "둔촌동", "명일동"],
             "life_area": ""},
            {"slug": "dunchon-dong", "name": "둔촌동", "priority": 2,
             "character": "올림픽파크포레온 대규모 재건축 단지가 들어선 신주거 권역",
             "landmarks": ["올림픽파크포레온", "둔촌동역", "일자산"],
             "nearby_stations": ["둔촌동역", "둔촌오륜역", "길동역"],
             "nearby_dongs": ["길동", "성내동", "명일동"],
             "life_area": ""},
            {"slug": "myeongil-dong", "name": "명일동", "priority": 2,
             "character": "명일근린공원과 학군 아파트가 자리한 조용한 주거지",
             "landmarks": ["명일근린공원", "명일역", "한영외고"],
             "nearby_stations": ["명일역", "고덕역", "굽은다리역"],
             "nearby_dongs": ["고덕동", "길동", "상일동"],
             "life_area": ""},
            {"slug": "godeok-dong", "name": "고덕동", "priority": 2,
             "character": "고덕그라시움 등 재건축 대단지가 밀집한 신흥 주거 권역",
             "landmarks": ["고덕그라시움", "고덕역", "샘터근린공원"],
             "nearby_stations": ["고덕역", "상일동역", "명일역"],
             "nearby_dongs": ["상일동", "명일동", "암사동"],
             "life_area": ""},
            {"slug": "sangil-dong", "name": "상일동", "priority": 2,
             "character": "고덕비즈밸리와 강동경희대병원이 자리한 업무·의료 권역",
             "landmarks": ["강동경희대병원", "고덕비즈밸리", "상일동역"],
             "nearby_stations": ["상일동역", "고덕역", "강일역"],
             "nearby_dongs": ["고덕동", "명일동", "둔촌동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "gwangjin-gu",
        "name": "광진구",
        "priority": 1,
        "trait": "건대 대학가 상권과 한강변 광장동 주거가 공존하는",
        "lead": "광진구는 건대입구 대학가 상권과 구의·자양의 업무·주거 권역, 광장동 "
                "한강변 고급 주거가 어우러진 자치구입니다. 젊은 유동인구와 숙박·먹자 "
                "상권이 밀집해 야간 시간대 방문 수요가 두드러지는 지역입니다.",
        "stations": ["건대입구역", "구의역", "강변역", "군자역"],
        "life_areas": ["건대·광진"],
        "dongs": [
            {"slug": "hwayang-dong", "name": "화양동", "priority": 1,
             "character": "건국대와 건대입구 먹자·숙박 상권이 밀집한 대학가 중심지",
             "landmarks": ["건국대학교", "건대입구역", "건대맛의거리"],
             "nearby_stations": ["건대입구역", "구의역", "어린이대공원역"],
             "nearby_dongs": ["자양동", "군자동", "구의동"],
             "life_area": "건대·광진"},
            {"slug": "jayang-dong", "name": "자양동", "priority": 1,
             "character": "뚝섬한강공원과 주상복합·먹자골목이 어우러진 주거·상업지",
             "landmarks": ["뚝섬한강공원", "자양동 양꼬치거리", "건대입구역"],
             "nearby_stations": ["건대입구역", "뚝섬유원지역", "구의역"],
             "nearby_dongs": ["화양동", "구의동", "광장동"],
             "life_area": "건대·광진"},
            {"slug": "guui-dong", "name": "구의동", "priority": 1,
             "character": "강변 테크노마트와 광진구청, 오피스텔이 모인 업무·상권 지역",
             "landmarks": ["강변 테크노마트", "광진구청", "구의역"],
             "nearby_stations": ["구의역", "강변역", "건대입구역"],
             "nearby_dongs": ["자양동", "광장동", "화양동"],
             "life_area": "건대·광진"},
            {"slug": "gunja-dong", "name": "군자동", "priority": 2,
             "character": "세종대 인근 주택가와 근린상권이 형성된 주거지",
             "landmarks": ["세종대학교", "군자역", "어린이대공원"],
             "nearby_stations": ["군자역", "어린이대공원역", "건대입구역"],
             "nearby_dongs": ["화양동", "중곡동", "능동"],
             "life_area": "건대·광진"},
            {"slug": "gwangjang-dong", "name": "광장동", "priority": 2,
             "character": "워커힐과 아차산 자락 한강변 고급 아파트가 자리한 정주 권역",
             "landmarks": ["워커힐", "아차산", "광나루역"],
             "nearby_stations": ["광나루역", "강변역", "구의역"],
             "nearby_dongs": ["구의동", "자양동", "중곡동"],
             "life_area": ""},
            {"slug": "junggok-dong", "name": "중곡동", "priority": 2,
             "character": "주택가와 재래시장, 국립정신건강센터가 있는 주거지",
             "landmarks": ["중곡제일시장", "국립정신건강센터", "중곡역"],
             "nearby_stations": ["중곡역", "군자역", "용마산역"],
             "nearby_dongs": ["군자동", "능동", "광장동"],
             "life_area": ""},
            {"slug": "neung-dong", "name": "능동", "priority": 2,
             "character": "어린이대공원을 낀 주거지와 공원 상권 지역",
             "landmarks": ["서울어린이대공원", "능동", "어린이대공원역"],
             "nearby_stations": ["어린이대공원역", "군자역", "건대입구역"],
             "nearby_dongs": ["군자동", "화양동", "중곡동"],
             "life_area": "건대·광진"},
        ],
    },
    {
        "slug": "seongdong-gu",
        "name": "성동구",
        "priority": 1,
        "trait": "성수 카페·IT 상권과 왕십리 교통 거점이 결합한",
        "lead": "성동구는 성수동 수제화·카페거리와 IT·스타트업 사옥, 왕십리 광역환승 "
                "거점이 어우러진 자치구입니다. 서울숲을 낀 신흥 상권과 옥수·금호의 "
                "한강변 주거가 함께 있어 평일과 주말의 방문 동선 성격이 다릅니다.",
        "stations": ["왕십리역", "성수역", "서울숲역", "옥수역", "금호역"],
        "life_areas": ["성수·왕십리"],
        "dongs": [
            {"slug": "seongsu-dong", "name": "성수동", "priority": 1,
             "character": "수제화거리에서 출발해 카페·갤러리·IT 사옥이 밀집한 신흥 상권",
             "landmarks": ["서울숲", "성수동 카페거리", "성수역"],
             "nearby_stations": ["성수역", "서울숲역", "뚝섬역"],
             "nearby_dongs": ["행당동", "응봉동", "금호동"],
             "life_area": "성수·왕십리"},
            {"slug": "haengdang-dong", "name": "행당동", "priority": 2,
             "character": "왕십리역 인접 주상복합과 대단지 아파트가 모인 주거·환승 권역",
             "landmarks": ["왕십리역", "행당역", "한양대학교"],
             "nearby_stations": ["왕십리역", "행당역", "마장역"],
             "nearby_dongs": ["마장동", "응봉동", "성수동"],
             "life_area": "성수·왕십리"},
            {"slug": "oksu-dong", "name": "옥수동", "priority": 2,
             "character": "한강·매봉산을 낀 고지대 아파트가 밀집한 정주 권역",
             "landmarks": ["옥수역", "달맞이봉공원", "동호대교"],
             "nearby_stations": ["옥수역", "금호역", "압구정역"],
             "nearby_dongs": ["금호동", "응봉동", "행당동"],
             "life_area": ""},
            {"slug": "geumho-dong", "name": "금호동", "priority": 2,
             "character": "재개발 아파트 단지가 들어선 언덕형 주거지",
             "landmarks": ["금호역", "금남시장", "응봉산"],
             "nearby_stations": ["금호역", "옥수역", "약수역"],
             "nearby_dongs": ["옥수동", "행당동", "응봉동"],
             "life_area": ""},
            {"slug": "majang-dong", "name": "마장동", "priority": 2,
             "character": "마장축산물시장 중심의 유통·도매와 주거 혼합지",
             "landmarks": ["마장축산물시장", "마장역", "청계천"],
             "nearby_stations": ["마장역", "왕십리역", "용두역"],
             "nearby_dongs": ["행당동", "성수동", "응봉동"],
             "life_area": "성수·왕십리"},
            {"slug": "eungbong-dong", "name": "응봉동", "priority": 2,
             "character": "응봉산 개나리와 한강변 아파트가 자리한 조용한 주거지",
             "landmarks": ["응봉산", "응봉역", "중랑천 합수부"],
             "nearby_stations": ["응봉역", "왕십리역", "옥수역"],
             "nearby_dongs": ["성수동", "행당동", "금호동"],
             "life_area": "성수·왕십리"},
        ],
    },
]
