# -*- coding: utf-8 -*-
"""성북·강북·도봉·노원 동북권 데이터."""

GU = [
    {
        "slug": "seongbuk-gu",
        "name": "성북구",
        "priority": 1,
        "trait": "대학가와 한옥 주거지, 구릉형 아파트촌이 어우러진",
        "lead": "성북구는 성신여대·고려대·한성대를 낀 대학 상권과 정릉·길음의 "
                "구릉형 주거지가 공존해 낮과 밤의 생활 리듬이 뚜렷하게 나뉩니다. "
                "내부순환로와 6호선·우이신설선이 동서를 잇지만 동네별 고저차가 "
                "커서 권역별 접근 동선을 따로 보는 편이 좋습니다.",
        "stations": ["성신여대입구역", "한성대입구역", "길음역", "월곡역", "돌곶이역", "석계역"],
        "life_areas": [],
        "dongs": [
            {"slug": "seongbuk-dong", "name": "성북동", "priority": 2,
             "character": "성북동 부촌과 한양도성, 미술관·고택이 모인 한적한 주거지",
             "landmarks": ["성북동 부촌", "길상사", "한양도성"],
             "nearby_stations": ["한성대입구역", "성신여대입구역"],
             "nearby_dongs": ["삼선동", "돈암동"],
             "life_area": ""},
            {"slug": "samseon-dong", "name": "삼선동", "priority": 2,
             "character": "한성대 캠퍼스와 삼선교 일대 노포 상권이 이어지는 대학가",
             "landmarks": ["한성대학교", "삼선교", "낙산공원 자락"],
             "nearby_stations": ["한성대입구역", "성신여대입구역"],
             "nearby_dongs": ["성북동", "동선동", "돈암동"],
             "life_area": ""},
            {"slug": "donam-dong", "name": "돈암동", "priority": 2,
             "character": "성신여대 상권과 대단지 아파트가 맞물린 주거·상업 혼합지",
             "landmarks": ["성신여대 거리", "돈암제일시장", "아리랑고개"],
             "nearby_stations": ["성신여대입구역", "한성대입구역", "길음역"],
             "nearby_dongs": ["삼선동", "정릉동", "길음동"],
             "life_area": ""},
            {"slug": "anam-dong", "name": "안암동", "priority": 2,
             "character": "고려대 캠퍼스를 중심으로 한 참살이길 대학 상권",
             "landmarks": ["고려대학교", "안암동 참살이길", "개운사"],
             "nearby_stations": ["월곡역", "돌곶이역"],
             "nearby_dongs": ["종암동", "보문동", "제기동"],
             "life_area": ""},
            {"slug": "jeongneung-dong", "name": "정릉동", "priority": 2,
             "character": "북한산 자락 구릉지에 빌라·아파트가 들어선 정주형 주거지",
             "landmarks": ["정릉(조선왕릉)", "국민대학교", "북한산 정릉탐방지원센터"],
             "nearby_stations": ["길음역", "성신여대입구역"],
             "nearby_dongs": ["길음동", "돈암동"],
             "life_area": ""},
            {"slug": "gireum-dong", "name": "길음동", "priority": 2,
             "character": "길음뉴타운 대단지 재개발로 형성된 신축 아파트촌",
             "landmarks": ["길음뉴타운", "길음역", "길음시장"],
             "nearby_stations": ["길음역", "성신여대입구역"],
             "nearby_dongs": ["정릉동", "돈암동", "월곡동"],
             "life_area": ""},
            {"slug": "jongam-dong", "name": "종암동", "priority": 2,
             "character": "고려대 인근 구릉 주거지와 종암사거리 생활 상권",
             "landmarks": ["종암사거리", "고려대 이공계캠퍼스", "북서울꿈의숲 인근"],
             "nearby_stations": ["월곡역", "돌곶이역", "길음역"],
             "nearby_dongs": ["안암동", "월곡동", "정릉동"],
             "life_area": ""},
            {"slug": "wolgok-dong", "name": "월곡동", "priority": 2,
             "character": "월곡역세권 주상복합과 동덕여대가 자리한 역세 주거지",
             "landmarks": ["월곡역", "동덕여자대학교", "월곡두산위브"],
             "nearby_stations": ["월곡역", "돌곶이역", "상월곡역"],
             "nearby_dongs": ["장위동", "종암동", "석관동"],
             "life_area": ""},
            {"slug": "jangwi-dong", "name": "장위동", "priority": 2,
             "character": "장위뉴타운 재개발이 진행 중인 대규모 주거 정비 권역",
             "landmarks": ["장위뉴타운", "장위시장", "돌곶이로"],
             "nearby_stations": ["돌곶이역", "석계역", "월곡역"],
             "nearby_dongs": ["석관동", "월곡동"],
             "life_area": ""},
            {"slug": "seokgwan-dong", "name": "석관동", "priority": 2,
             "character": "석계역세권과 의릉, 한국예술종합학교가 있는 동부 경계 주거지",
             "landmarks": ["의릉", "한국예술종합학교", "석계역"],
             "nearby_stations": ["석계역", "돌곶이역"],
             "nearby_dongs": ["장위동", "월곡동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "gangbuk-gu",
        "name": "강북구",
        "priority": 1,
        "trait": "북한산을 등진 구릉지에 노후 주거와 재정비촌이 섞인",
        "lead": "강북구는 수유·미아 일대 생활 상권과 북한산·우이천을 낀 구릉형 "
                "주거지가 중심을 이루는 자치구입니다. 우이신설선과 4호선이 남북을 "
                "잇지만 경사진 골목이 많아 동네별로 접근 난이도가 달라 권역을 "
                "구분해 살피는 편이 좋습니다.",
        "stations": ["수유역", "미아역", "미아사거리역", "북한산우이역"],
        "life_areas": [],
        "dongs": [
            {"slug": "suyu-dong", "name": "수유동", "priority": 2,
             "character": "수유역 광역 상권과 4·19로 먹자골목이 형성된 강북 중심지",
             "landmarks": ["수유역", "4.19민주묘지", "북한산 우이분소"],
             "nearby_stations": ["수유역", "미아역", "북한산우이역"],
             "nearby_dongs": ["미아동", "우이동", "삼양동"],
             "life_area": ""},
            {"slug": "mia-dong", "name": "미아동", "priority": 2,
             "character": "미아사거리역 상권과 송중·송천 일대 대단지 주거가 섞인 권역",
             "landmarks": ["미아사거리역", "롯데백화점 미아점", "숭곡시장"],
             "nearby_stations": ["미아사거리역", "미아역", "수유역"],
             "nearby_dongs": ["번동", "삼양동", "수유동"],
             "life_area": ""},
            {"slug": "beon-dong", "name": "번동", "priority": 2,
             "character": "북서울꿈의숲을 끼고 아파트 단지가 들어선 주거 정주지",
             "landmarks": ["북서울꿈의숲", "오패산", "번동주공아파트"],
             "nearby_stations": ["미아사거리역", "미아역"],
             "nearby_dongs": ["미아동", "삼양동"],
             "life_area": ""},
            {"slug": "ui-dong", "name": "우이동", "priority": 2,
             "character": "북한산우이역 종점과 우이천 계곡 입구가 자리한 산자락 권역",
             "landmarks": ["북한산우이역", "우이동 계곡", "도선사 입구"],
             "nearby_stations": ["북한산우이역", "수유역"],
             "nearby_dongs": ["수유동", "삼양동"],
             "life_area": ""},
            {"slug": "samyang-dong", "name": "삼양동", "priority": 2,
             "character": "삼양로 따라 노후 주택가와 우이신설선 역세권이 이어지는 구릉 주거지",
             "landmarks": ["삼양사거리", "솔밭근린공원", "화계사 인근"],
             "nearby_stations": ["북한산우이역", "수유역"],
             "nearby_dongs": ["수유동", "미아동", "우이동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "dobong-gu",
        "name": "도봉구",
        "priority": 1,
        "trait": "도봉산을 배경으로 대단지 아파트와 옛 주거지가 공존하는",
        "lead": "도봉구는 창동 역세권 개발지와 쌍문·방학의 오래된 주거지, 도봉산 "
                "자락이 함께 자리한 서울 북단 자치구입니다. 1·4호선과 광역철도가 "
                "지나 외곽 접근은 편하지만 산자락 경계 동네는 동선이 길어 권역을 "
                "나눠 보는 편이 좋습니다.",
        "stations": ["창동역", "쌍문역", "방학역", "도봉역", "도봉산역"],
        "life_areas": [],
        "dongs": [
            {"slug": "chang-dong", "name": "창동", "priority": 2,
             "character": "창동 역세권 개발과 아레나·플랫폼창동이 들어선 대단지 권역",
             "landmarks": ["창동역", "플랫폼창동61", "창동 아레나 부지"],
             "nearby_stations": ["창동역", "쌍문역"],
             "nearby_dongs": ["쌍문동", "방학동"],
             "life_area": ""},
            {"slug": "ssangmun-dong", "name": "쌍문동", "priority": 2,
             "character": "쌍문역 생활 상권과 오래된 주공·연립 주거가 모인 정주지",
             "landmarks": ["쌍문역", "쌍문근린공원", "둘리뮤지엄"],
             "nearby_stations": ["쌍문역", "창동역", "방학역"],
             "nearby_dongs": ["창동", "방학동"],
             "life_area": ""},
            {"slug": "banghak-dong", "name": "방학동", "priority": 2,
             "character": "도봉산 자락 아파트촌과 정의공주묘가 있는 북부 주거지",
             "landmarks": ["방학역", "연산군묘", "도봉산 둘레길 입구"],
             "nearby_stations": ["방학역", "쌍문역", "도봉역"],
             "nearby_dongs": ["쌍문동", "도봉동", "창동"],
             "life_area": ""},
            {"slug": "dobong-dong", "name": "도봉동", "priority": 2,
             "character": "도봉산역 등산 관문과 서울 최북단 주거지가 맞닿은 산자락 권역",
             "landmarks": ["도봉산역", "도봉산 탐방지원센터", "도봉서원 터"],
             "nearby_stations": ["도봉산역", "도봉역", "방학역"],
             "nearby_dongs": ["방학동", "쌍문동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "nowon-gu",
        "name": "노원구",
        "priority": 1,
        "trait": "대규모 아파트 단지와 학원가, 대학이 밀집한",
        "lead": "노원구는 상계·중계의 대규모 아파트 단지와 노원역 중심 상권, "
                "중계동 학원가가 어우러진 서울 동북권의 대표 주거 자치구입니다. "
                "4·7호선이 교차하는 노원역을 축으로 생활권이 모여 있어 단지별 "
                "접근 동선이 비교적 명확한 편입니다.",
        "stations": ["노원역", "상계역", "중계역", "하계역", "공릉역", "석계역"],
        "life_areas": ["노원·상계"],
        "dongs": [
            {"slug": "sanggye-dong", "name": "상계동", "priority": 1,
             "character": "상계주공 대단지와 노원역 중심 상권이 결합한 동북권 핵심 주거지",
             "landmarks": ["노원역", "상계주공아파트", "수락산 입구"],
             "nearby_stations": ["노원역", "상계역"],
             "nearby_dongs": ["중계동", "월계동"],
             "life_area": "노원·상계"},
            {"slug": "junggye-dong", "name": "중계동", "priority": 1,
             "character": "은행사거리 학원가와 중계택지 대단지가 자리한 교육 중심 주거지",
             "landmarks": ["은행사거리 학원가", "중계근린공원", "등나무근린공원"],
             "nearby_stations": ["중계역", "하계역", "노원역"],
             "nearby_dongs": ["상계동", "하계동"],
             "life_area": "노원·상계"},
            {"slug": "hagye-dong", "name": "하계동", "priority": 2,
             "character": "하계역세권 아파트 단지와 한글비석로 생활 상권이 이어지는 주거지",
             "landmarks": ["하계역", "한글비석로", "서울과학기술대 인근"],
             "nearby_stations": ["하계역", "중계역", "공릉역"],
             "nearby_dongs": ["중계동", "공릉동"],
             "life_area": "노원·상계"},
            {"slug": "gongneung-dong", "name": "공릉동", "priority": 2,
             "character": "서울과기대·삼육대 대학가와 경춘선숲길이 지나는 주거 상권",
             "landmarks": ["서울과학기술대학교", "경춘선숲길", "공릉역"],
             "nearby_stations": ["공릉역", "석계역", "하계역"],
             "nearby_dongs": ["하계동", "월계동"],
             "life_area": "노원·상계"},
            {"slug": "wolgye-dong", "name": "월계동", "priority": 2,
             "character": "광운대역 일대와 초안산을 낀 노후 주거 및 재정비 권역",
             "landmarks": ["광운대학교", "초안산근린공원", "월계동 인덕대"],
             "nearby_stations": ["석계역", "상계역", "노원역"],
             "nearby_dongs": ["공릉동", "상계동"],
             "life_area": "노원·상계"},
        ],
    },
]
