# -*- coding: utf-8 -*-
"""서남권 자치구 데이터 (영등포·구로·금천·동작·관악)."""

GU = [
    {
        "slug": "yeongdeungpo-gu",
        "name": "영등포구",
        "priority": 1,
        "trait": "여의도 금융업무지구와 영등포 구도심 상권이 맞물린",
        "lead": "영등포구는 여의도 금융·방송 업무지구와 영등포 역세권 구도심이 함께 있어 "
                "평일 낮과 저녁의 수요 흐름이 뚜렷하게 갈리는 자치구입니다. 문래·당산의 "
                "신상권과 한강변 주거가 더해져 방문 동선이 한강 남북으로 넓게 펼쳐집니다.",
        "stations": ["여의도역", "영등포역", "당산역", "문래역", "신길역", "대림역"],
        "life_areas": ["여의도·영등포", "문래·당산"],
        "dongs": [
            {"slug": "yeouido-dong", "name": "여의도동", "priority": 1,
             "character": "증권·방송사가 밀집한 금융 업무지구이자 한강공원 권역",
             "landmarks": ["국회의사당", "IFC몰", "여의도한강공원"],
             "nearby_stations": ["여의도역", "여의나루역", "국회의사당역"],
             "nearby_dongs": ["영등포동", "신길동", "당산동"],
             "life_area": "여의도·영등포"},
            {"slug": "yeongdeungpo-dong", "name": "영등포동", "priority": 1,
             "character": "영등포역과 타임스퀘어를 낀 전통 역세권 상업지",
             "landmarks": ["타임스퀘어", "영등포역", "영등포시장"],
             "nearby_stations": ["영등포역", "신길역", "문래역"],
             "nearby_dongs": ["여의도동", "신길동", "문래동"],
             "life_area": "여의도·영등포"},
            {"slug": "dangsan-dong", "name": "당산동", "priority": 1,
             "character": "당산역 환승과 한강변 아파트가 어우러진 주거·교통 요지",
             "landmarks": ["당산역", "당산철교", "선유도공원"],
             "nearby_stations": ["당산역", "문래역", "여의나루역"],
             "nearby_dongs": ["문래동", "양평동", "여의도동"],
             "life_area": "문래·당산"},
            {"slug": "mullae-dong", "name": "문래동", "priority": 1,
             "character": "철공소 골목이 예술촌으로 변신한 문래창작촌 권역",
             "landmarks": ["문래창작촌", "문래역", "영등포공원"],
             "nearby_stations": ["문래역", "영등포역", "당산역"],
             "nearby_dongs": ["당산동", "양평동", "영등포동"],
             "life_area": "문래·당산"},
            {"slug": "singil-dong", "name": "신길동", "priority": 1,
             "character": "재개발 아파트와 골목 상권이 섞인 주거 밀집지",
             "landmarks": ["신길역", "신길뉴타운", "영등포로터리"],
             "nearby_stations": ["신길역", "영등포역", "대방역"],
             "nearby_dongs": ["영등포동", "대림동", "여의도동"],
             "life_area": "여의도·영등포"},
            {"slug": "daerim-dong", "name": "대림동", "priority": 2,
             "character": "중국동포 상권과 대림중앙시장이 자리한 다문화 생활권",
             "landmarks": ["대림역", "대림중앙시장", "대림차이나타운"],
             "nearby_stations": ["대림역", "신도림역", "신길역"],
             "nearby_dongs": ["신길동", "구로동", "양평동"],
             "life_area": ""},
            {"slug": "yangpyeong-dong", "name": "양평동", "priority": 2,
             "character": "준공업지대와 한강변 신축 단지가 공존하는 권역",
             "landmarks": ["선유도역", "양화한강공원", "이마트 양평점"],
             "nearby_stations": ["당산역", "문래역", "여의나루역"],
             "nearby_dongs": ["당산동", "문래동", "대림동"],
             "life_area": "문래·당산"},
        ],
    },
    {
        "slug": "guro-gu",
        "name": "구로구",
        "priority": 1,
        "trait": "구로디지털단지 IT오피스와 옛 공단 주거가 섞인",
        "lead": "구로구는 구로디지털단지의 IT·벤처 오피스 밀집지와 신도림 환승 상권이 "
                "중심을 이루는 자치구입니다. 가리봉·개봉 등 옛 공단 배후 주거지가 넓게 "
                "퍼져 있어 업무지와 생활권이 한 동선 안에 맞물리는 편입니다.",
        "stations": ["신도림역", "구로역", "구로디지털단지역", "남구로역", "개봉역"],
        "life_areas": ["구디·가디"],
        "dongs": [
            {"slug": "guro-dong", "name": "구로동", "priority": 1,
             "character": "구로디지털단지 IT오피스와 배후 주거가 밀집한 중심지",
             "landmarks": ["구로디지털단지역", "지플러스타워", "구로마트"],
             "nearby_stations": ["구로디지털단지역", "남구로역", "신도림역"],
             "nearby_dongs": ["가리봉동", "신도림동", "대림동"],
             "life_area": "구디·가디"},
            {"slug": "sindorim-dong", "name": "신도림동", "priority": 1,
             "character": "1·2호선 환승과 디큐브시티가 결합한 교통·상업 요지",
             "landmarks": ["신도림역", "디큐브시티", "테크노마트"],
             "nearby_stations": ["신도림역", "구로역", "대림역"],
             "nearby_dongs": ["구로동", "문래동", "고척동"],
             "life_area": "구디·가디"},
            {"slug": "garibong-dong", "name": "가리봉동", "priority": 1,
             "character": "옛 공단 배후 골목과 다문화 상권이 남은 주거지",
             "landmarks": ["남구로역", "가리봉시장", "마리오아울렛"],
             "nearby_stations": ["남구로역", "구로디지털단지역", "가산디지털단지역"],
             "nearby_dongs": ["구로동", "가산동", "독산동"],
             "life_area": "구디·가디"},
            {"slug": "gaebong-dong", "name": "개봉동", "priority": 1,
             "character": "안양천변 대단지 아파트가 자리한 주거 중심지",
             "landmarks": ["개봉역", "개봉시장", "안양천"],
             "nearby_stations": ["개봉역", "구로역", "신도림역"],
             "nearby_dongs": ["고척동", "오류동", "구로동"],
             "life_area": ""},
            {"slug": "gocheok-dong", "name": "고척동", "priority": 2,
             "character": "고척스카이돔과 안양천을 낀 주거·체육 권역",
             "landmarks": ["고척스카이돔", "안양천", "고척근린공원"],
             "nearby_stations": ["구로역", "개봉역", "신도림역"],
             "nearby_dongs": ["개봉동", "구로동", "오류동"],
             "life_area": ""},
            {"slug": "oryu-dong", "name": "오류동", "priority": 2,
             "character": "경인로변 역세권과 단독·다세대 주거가 섞인 권역",
             "landmarks": ["오류동역", "오류시장", "동부제일병원"],
             "nearby_stations": ["개봉역", "구로역", "신도림역"],
             "nearby_dongs": ["개봉동", "항동", "고척동"],
             "life_area": ""},
            {"slug": "hang-dong", "name": "항동", "priority": 2,
             "character": "항동지구 택지개발로 들어선 신규 아파트 권역",
             "landmarks": ["항동철길", "푸른수목원", "항동지구"],
             "nearby_stations": ["개봉역", "오류동역", "구로역"],
             "nearby_dongs": ["오류동", "개봉동", "고척동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "geumcheon-gu",
        "name": "금천구",
        "priority": 1,
        "trait": "가산디지털단지 지식산업센터가 밀집한",
        "lead": "금천구는 가산디지털단지의 지식산업센터와 패션아울렛 상권이 핵심을 "
                "이루는 자치구입니다. 독산·시흥의 주거지가 단지를 둘러싸고 있어 출퇴근 "
                "인구와 정주 인구의 동선이 한데 겹치는 특징이 있습니다.",
        "stations": ["가산디지털단지역", "독산역", "금천구청역"],
        "life_areas": ["구디·가디"],
        "dongs": [
            {"slug": "gasan-dong", "name": "가산동", "priority": 1,
             "character": "지식산업센터와 패션아울렛이 밀집한 업무·쇼핑 중심지",
             "landmarks": ["가산디지털단지역", "마리오아울렛", "현대시티아울렛"],
             "nearby_stations": ["가산디지털단지역", "독산역", "남구로역"],
             "nearby_dongs": ["독산동", "구로동", "가리봉동"],
             "life_area": "구디·가디"},
            {"slug": "doksan-dong", "name": "독산동", "priority": 1,
             "character": "우시장 상권과 빌라 밀집 주거지가 어우러진 권역",
             "landmarks": ["독산역", "독산동우시장", "금천현대시장"],
             "nearby_stations": ["독산역", "가산디지털단지역", "금천구청역"],
             "nearby_dongs": ["가산동", "시흥동", "구로동"],
             "life_area": "구디·가디"},
            {"slug": "siheung-dong", "name": "시흥동", "priority": 1,
             "character": "관악산 자락과 시흥대로변 주거가 펼쳐진 권역",
             "landmarks": ["금천구청역", "은행나무시장", "호암산"],
             "nearby_stations": ["금천구청역", "독산역", "관악역"],
             "nearby_dongs": ["독산동", "가산동", "신림동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "dongjak-gu",
        "name": "동작구",
        "priority": 1,
        "trait": "노량진 학원가와 한강변 주거가 어우러진",
        "lead": "동작구는 노량진 학원가와 수산시장, 상도·사당의 대단지 주거가 함께 있는 "
                "자치구입니다. 한강과 관악산 사이 구릉지에 동네가 자리해 역세권마다 "
                "수요 성격이 다르게 나타나는 편입니다.",
        "stations": ["노량진역", "흑석역", "상도역", "사당역", "이수역", "대방역"],
        "life_areas": [],
        "dongs": [
            {"slug": "noryangjin-dong", "name": "노량진동", "priority": 1,
             "character": "수험가 고시촌과 수산시장이 공존하는 권역",
             "landmarks": ["노량진수산시장", "노량진역", "사육신공원"],
             "nearby_stations": ["노량진역", "대방역", "상도역"],
             "nearby_dongs": ["상도동", "대방동", "흑석동"],
             "life_area": ""},
            {"slug": "sangdo-dong", "name": "상도동", "priority": 1,
             "character": "숭실대 일대와 구릉지 대단지 아파트가 자리한 주거지",
             "landmarks": ["상도역", "숭실대학교", "국사봉"],
             "nearby_stations": ["상도역", "노량진역", "장승배기역"],
             "nearby_dongs": ["노량진동", "흑석동", "신대방동"],
             "life_area": ""},
            {"slug": "heukseok-dong", "name": "흑석동", "priority": 1,
             "character": "중앙대와 한강변 재개발 단지가 결합한 권역",
             "landmarks": ["흑석역", "중앙대학교", "효사정"],
             "nearby_stations": ["흑석역", "노량진역", "상도역"],
             "nearby_dongs": ["노량진동", "상도동", "사당동"],
             "life_area": ""},
            {"slug": "sadang-dong", "name": "사당동", "priority": 1,
             "character": "사당역 환승과 먹자상권을 낀 교통·주거 요지",
             "landmarks": ["사당역", "이수역", "남성사계시장"],
             "nearby_stations": ["사당역", "이수역", "낙성대역"],
             "nearby_dongs": ["흑석동", "상도동", "봉천동"],
             "life_area": "신림·관악"},
            {"slug": "daebang-dong", "name": "대방동", "priority": 2,
             "character": "여의도 배후 주거와 보라매공원을 낀 권역",
             "landmarks": ["대방역", "보라매공원", "성남중학교"],
             "nearby_stations": ["대방역", "노량진역", "신길역"],
             "nearby_dongs": ["노량진동", "신대방동", "상도동"],
             "life_area": ""},
            {"slug": "sindaebang-dong", "name": "신대방동", "priority": 2,
             "character": "보라매공원과 대단지 아파트가 어우러진 주거 권역",
             "landmarks": ["보라매공원", "신대방삼거리역", "기상청"],
             "nearby_stations": ["대방역", "상도역", "신림역"],
             "nearby_dongs": ["대방동", "상도동", "신림동"],
             "life_area": "신림·관악"},
        ],
    },
    {
        "slug": "gwanak-gu",
        "name": "관악구",
        "priority": 1,
        "trait": "서울대와 신림·봉천 청년 주거가 밀집한",
        "lead": "관악구는 서울대학교와 신림·봉천의 1인 가구 밀집 주거가 중심을 이루는 "
                "자치구입니다. 관악산 자락을 따라 골목 상권과 원룸촌이 넓게 퍼져 있어 "
                "젊은 인구 비중이 높고 생활 동선이 촘촘한 편입니다.",
        "stations": ["신림역", "서울대입구역", "봉천역", "낙성대역"],
        "life_areas": ["신림·관악", "서울대입구·봉천"],
        "dongs": [
            {"slug": "sillim-dong", "name": "신림동", "priority": 1,
             "character": "신림역 번화가와 고시촌·원룸촌이 밀집한 청년 상권",
             "landmarks": ["신림역", "순대타운", "서울대"],
             "nearby_stations": ["신림역", "서울대입구역", "봉천역"],
             "nearby_dongs": ["봉천동", "서원동", "남현동"],
             "life_area": "신림·관악"},
            {"slug": "bongcheon-dong", "name": "봉천동", "priority": 1,
             "character": "서울대입구역 상권과 구릉지 주거가 결합한 생활 중심지",
             "landmarks": ["서울대입구역", "봉천역", "관악구청"],
             "nearby_stations": ["서울대입구역", "봉천역", "낙성대역"],
             "nearby_dongs": ["신림동", "남현동", "서원동"],
             "life_area": "서울대입구·봉천"},
            {"slug": "namhyeon-dong", "name": "남현동", "priority": 1,
             "character": "사당 인접 주거지로 예술인마을이 자리한 권역",
             "landmarks": ["낙성대역", "예술인마을", "관악산"],
             "nearby_stations": ["낙성대역", "사당역", "서울대입구역"],
             "nearby_dongs": ["봉천동", "신림동", "사당동"],
             "life_area": "서울대입구·봉천"},
            {"slug": "seowon-dong", "name": "서원동", "priority": 2,
             "character": "신림역 서편 원룸촌과 재래시장이 자리한 주거 권역",
             "landmarks": ["신원시장", "신림역", "관악산공원"],
             "nearby_stations": ["신림역", "서울대입구역", "봉천역"],
             "nearby_dongs": ["신림동", "봉천동", "남현동"],
             "life_area": "신림·관악"},
        ],
    },
]
