# -*- coding: utf-8 -*-
"""2차 확장 구(강동·강북·도봉·동대문·서대문·성북) 역세권 데이터.

노선 커버리지 확장용. 단계적 색인 정책에 따라 priority=2(빌드+noindex)이며,
지하철역 안내의 1~9호선 노선도에는 노출되어 내부링크로 연결된다.
"""

STATIONS2 = [
    # ── 강동구 (5·8·9호선) ──────────────────────────────
    {"slug": "cheonho-station", "name": "천호역", "priority": 2,
     "lines": ["5호선", "8호선"], "nearby_dongs": ["천호동", "성내동", "암사동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "강동 최대 상권과 백화점을 낀 5·8호선 환승역"},
    {"slug": "gangdong-station", "name": "강동역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["천호동", "길동", "성내동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "5호선 본선·분기가 갈리는 주거·상업 지역"},
    {"slug": "amsa-station", "name": "암사역", "priority": 2,
     "lines": ["8호선"], "nearby_dongs": ["암사동", "성내동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "선사유적과 대단지 주거가 자리한 8호선 종착권"},
    {"slug": "gil-dong-station", "name": "길동역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["길동", "성내동", "둔촌동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "주거와 근린 상권이 섞인 5호선 역세권"},
    {"slug": "dunchon-dong-station", "name": "둔촌동역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["둔촌동", "길동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "대규모 재건축 단지가 들어선 주거 중심지"},
    {"slug": "godeok-station", "name": "고덕역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["고덕동", "상일동", "명일동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "신축 아파트 단지가 밀집한 정주 권역"},
    {"slug": "sangil-dong-station", "name": "상일동역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["상일동", "고덕동"],
     "nearby_gu": ["강동구"], "life_area": "",
     "character": "고덕비즈니스밸리와 주거가 함께 개발되는 권역"},

    # ── 강북구 (4호선·우이신설선) ───────────────────────
    {"slug": "suyu-station", "name": "수유역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["수유동", "미아동", "번동"],
     "nearby_gu": ["강북구"], "life_area": "",
     "character": "강북 대표 상권과 버스 환승이 모이는 4호선 역"},
    {"slug": "mia-station", "name": "미아역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["미아동", "번동"],
     "nearby_gu": ["강북구"], "life_area": "",
     "character": "대단지 주거가 배후인 4호선 역세권"},
    {"slug": "mia-sageori-station", "name": "미아사거리역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["미아동", "길음동", "송중동"],
     "nearby_gu": ["강북구", "성북구"], "life_area": "",
     "character": "백화점·상권이 형성된 강북·성북 접경 환승 상권"},
    {"slug": "bukhansan-ui-station", "name": "북한산우이역", "priority": 2,
     "lines": ["우이신설선"], "nearby_dongs": ["우이동", "수유동"],
     "nearby_gu": ["강북구"], "life_area": "",
     "character": "북한산 등산로와 주거가 맞닿은 우이신설선 종점"},

    # ── 도봉구 (1·4·7호선) ──────────────────────────────
    {"slug": "chang-dong-station", "name": "창동역", "priority": 2,
     "lines": ["1호선", "4호선"], "nearby_dongs": ["창동", "쌍문동"],
     "nearby_gu": ["도봉구"], "life_area": "",
     "character": "복합 개발이 진행되는 1·4호선 환승 거점"},
    {"slug": "ssangmun-station", "name": "쌍문역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["쌍문동", "창동"],
     "nearby_gu": ["도봉구"], "life_area": "",
     "character": "오래된 주거지와 근린 상권이 자리한 4호선 역"},
    {"slug": "banghak-station", "name": "방학역", "priority": 2,
     "lines": ["1호선"], "nearby_dongs": ["방학동", "쌍문동", "도봉동"],
     "nearby_gu": ["도봉구"], "life_area": "",
     "character": "북한산 자락 주거권의 1호선 역세권"},
    {"slug": "dobong-station", "name": "도봉역", "priority": 2,
     "lines": ["1호선"], "nearby_dongs": ["도봉동", "방학동"],
     "nearby_gu": ["도봉구"], "life_area": "",
     "character": "주거 단지와 산자락이 인접한 1호선 역"},
    {"slug": "dobongsan-station", "name": "도봉산역", "priority": 2,
     "lines": ["1호선", "7호선"], "nearby_dongs": ["도봉동"],
     "nearby_gu": ["도봉구"], "life_area": "",
     "character": "도봉산 등산 관문이자 1·7호선 환승역"},

    # ── 동대문구 (1·2·5호선·경의중앙·우이신설) ──────────
    {"slug": "cheongnyangni-station", "name": "청량리역", "priority": 2,
     "lines": ["1호선", "수인분당선", "경의중앙선", "경춘선"],
     "nearby_dongs": ["청량리동", "전농동", "용신동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "수도권 동북부 광역 환승과 상권이 모이는 거점역"},
    {"slug": "hoegi-station", "name": "회기역", "priority": 2,
     "lines": ["1호선", "경의중앙선"], "nearby_dongs": ["회기동", "휘경동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "경희대·시립대 대학가가 배후인 1호선 역"},
    {"slug": "hufs-station", "name": "외대앞역", "priority": 2,
     "lines": ["1호선"], "nearby_dongs": ["이문동", "휘경동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "한국외대 대학가 원룸·상권이 형성된 역세권"},
    {"slug": "sinseol-dong-station", "name": "신설동역", "priority": 2,
     "lines": ["1호선", "2호선", "우이신설선"], "nearby_dongs": ["신설동", "용두동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "1·2호선과 우이신설선이 만나는 도심 접경 환승역"},
    {"slug": "janghanpyeong-station", "name": "장한평역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["장안동", "답십리동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "자동차 부품 상권과 주거가 섞인 5호선 역"},
    {"slug": "dapsimni-station", "name": "답십리역", "priority": 2,
     "lines": ["5호선"], "nearby_dongs": ["답십리동", "전농동"],
     "nearby_gu": ["동대문구"], "life_area": "",
     "character": "재정비로 신축 주거가 늘어난 5호선 역세권"},

    # ── 서대문구 (2·3호선·경의중앙) ─────────────────────
    {"slug": "sinchon-station", "name": "신촌역", "priority": 2,
     "lines": ["2호선"], "nearby_dongs": ["신촌동", "연희동", "창천동"],
     "nearby_gu": ["서대문구"], "life_area": "",
     "character": "연·이대 대학 상권의 중심이 되는 2호선 역"},
    {"slug": "ewha-womans-univ-station", "name": "이대역", "priority": 2,
     "lines": ["2호선"], "nearby_dongs": ["대현동", "신촌동"],
     "nearby_gu": ["서대문구"], "life_area": "",
     "character": "이화여대 패션·뷰티 상권이 형성된 2호선 역"},
    {"slug": "hongje-station", "name": "홍제역", "priority": 2,
     "lines": ["3호선"], "nearby_dongs": ["홍제동", "홍은동"],
     "nearby_gu": ["서대문구"], "life_area": "",
     "character": "인왕산 자락 대단지 주거권의 3호선 역"},
    {"slug": "muakjae-station", "name": "무악재역", "priority": 2,
     "lines": ["3호선"], "nearby_dongs": ["홍제동", "현저동"],
     "nearby_gu": ["서대문구"], "life_area": "",
     "character": "고개를 낀 주거지가 배후인 3호선 역"},
    {"slug": "gajwa-station", "name": "가좌역", "priority": 2,
     "lines": ["경의중앙선"], "nearby_dongs": ["남가좌동", "북가좌동"],
     "nearby_gu": ["서대문구"], "life_area": "",
     "character": "가재울뉴타운 신축 주거가 들어선 경의중앙선 역"},

    # ── 성북구 (1·4·6호선·우이신설) ─────────────────────
    {"slug": "sungshin-womens-univ-station", "name": "성신여대입구역", "priority": 2,
     "lines": ["4호선", "우이신설선"], "nearby_dongs": ["동선동", "돈암동", "삼선동"],
     "nearby_gu": ["성북구"], "life_area": "",
     "character": "성신여대 상권과 주거가 맞물린 4·우이신설 환승역"},
    {"slug": "hansung-univ-station", "name": "한성대입구역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["삼선동", "동소문동", "성북동"],
     "nearby_gu": ["성북구"], "life_area": "",
     "character": "한성대·성북동 주거와 카페 거리가 인접한 4호선 역"},
    {"slug": "gireum-station", "name": "길음역", "priority": 2,
     "lines": ["4호선"], "nearby_dongs": ["길음동", "정릉동"],
     "nearby_gu": ["성북구"], "life_area": "",
     "character": "뉴타운 대단지 주거가 형성된 4호선 역세권"},
    {"slug": "wolgok-station", "name": "월곡역", "priority": 2,
     "lines": ["6호선"], "nearby_dongs": ["하월곡동", "상월곡동"],
     "nearby_gu": ["성북구"], "life_area": "",
     "character": "재정비 주거와 근린 상권이 자리한 6호선 역"},
    {"slug": "dolgoji-station", "name": "돌곶이역", "priority": 2,
     "lines": ["6호선"], "nearby_dongs": ["석관동", "장위동"],
     "nearby_gu": ["성북구"], "life_area": "",
     "character": "주거 밀집권을 잇는 6호선 역세권"},
    {"slug": "seokgye-station", "name": "석계역", "priority": 2,
     "lines": ["1호선", "6호선"], "nearby_dongs": ["석관동", "장위동"],
     "nearby_gu": ["성북구", "노원구"], "life_area": "",
     "character": "성북·노원 접경의 1·6호선 환승 역세권"},
]
