# -*- coding: utf-8 -*-
"""도심권 자치구 데이터 (용산·종로·중·동대문·중랑)."""

GU = [
    {
        "slug": "yongsan-gu",
        "name": "용산구",
        "priority": 1,
        "trait": "한강과 도심을 잇는 교통 요지에 국제 상권이 어우러진",
        "lead": "용산구는 용산역 일대 업무·역세권과 이태원·한남의 국제적인 주거·상권이 "
                "공존해 위치별로 분위기 차이가 큰 자치구입니다. 외국인 거주가 많고 호텔과 "
                "오피스텔이 곳곳에 자리해 방문형 관리 동선이 비교적 또렷한 편입니다.",
        "stations": ["용산역", "이태원역", "한강진역", "삼각지역", "숙대입구역"],
        "life_areas": ["용산·서울역", "한남·이태원"],
        "dongs": [
            {"slug": "hannam-dong", "name": "한남동", "priority": 1,
             "character": "대사관과 고급 주택, 한강뷰 단지가 모인 국제적인 주거 권역",
             "landmarks": ["한남대교", "리움미술관", "유엔빌리지"],
             "nearby_stations": ["한강진역", "이태원역", "약수역"],
             "nearby_dongs": ["이태원동", "보광동", "한강로동"],
             "life_area": "한남·이태원"},
            {"slug": "itaewon-dong", "name": "이태원동", "priority": 1,
             "character": "다국적 상권과 외국인 거주가 밀집한 국제 거리",
             "landmarks": ["이태원거리", "녹사평", "해방촌"],
             "nearby_stations": ["이태원역", "한강진역", "녹사평역"],
             "nearby_dongs": ["한남동", "보광동", "후암동"],
             "life_area": "한남·이태원"},
            {"slug": "hangangno-dong", "name": "한강로동", "priority": 1,
             "character": "용산역 역세권과 고층 주상복합·전자상가가 어우러진 도심 권역",
             "landmarks": ["용산역", "아이파크몰", "용산전자상가"],
             "nearby_stations": ["용산역", "신용산역", "삼각지역"],
             "nearby_dongs": ["이촌동", "한남동", "청파동"],
             "life_area": "용산·서울역"},
            {"slug": "ichon-dong", "name": "이촌동", "priority": 2,
             "character": "한강변 대단지 아파트가 늘어선 정주형 주거지",
             "landmarks": ["이촌한강공원", "국립중앙박물관", "동부이촌동"],
             "nearby_stations": ["이촌역", "용산역", "신용산역"],
             "nearby_dongs": ["한강로동", "보광동", "후암동"],
             "life_area": "용산·서울역"},
            {"slug": "huam-dong", "name": "후암동", "priority": 2,
             "character": "남산 자락의 오래된 주택가와 골목 상권이 남은 동네",
             "landmarks": ["남산", "후암동 골목길", "용산도서관"],
             "nearby_stations": ["서울역", "숙대입구역", "삼각지역"],
             "nearby_dongs": ["청파동", "이태원동", "한강로동"],
             "life_area": "용산·서울역"},
            {"slug": "cheongpa-dong", "name": "청파동", "priority": 2,
             "character": "숙명여대 인근의 학교·주택가가 어우러진 생활권",
             "landmarks": ["숙명여자대학교", "청파언덕", "효창공원"],
             "nearby_stations": ["숙대입구역", "서울역", "삼각지역"],
             "nearby_dongs": ["후암동", "한강로동", "이촌동"],
             "life_area": "용산·서울역"},
            {"slug": "bogwang-dong", "name": "보광동", "priority": 2,
             "character": "한강진과 이태원 사이 언덕 주택가가 이어지는 주거지",
             "landmarks": ["보광동 시장", "한강진역 일대", "서빙고"],
             "nearby_stations": ["한강진역", "이태원역", "이촌역"],
             "nearby_dongs": ["한남동", "이태원동", "이촌동"],
             "life_area": "한남·이태원"},
        ],
    },
    {
        "slug": "jongno-gu",
        "name": "종로구",
        "priority": 1,
        "trait": "궁궐과 한옥, 도심 업무지구가 한데 어우러진",
        "lead": "종로구는 광화문 업무지구와 인사동·삼청동의 전통 상권, 북악 자락의 "
                "조용한 주택가가 공존하는 서울의 옛 중심입니다. 관광지와 오피스가 가까이 "
                "있어 시간대에 따라 방문 수요가 또렷하게 나뉘는 편입니다.",
        "stations": ["종각역", "종로3가역", "광화문역", "경복궁역", "안국역", "혜화역"],
        "life_areas": ["종로·광화문"],
        "dongs": [
            {"slug": "hyehwa-dong", "name": "혜화동", "priority": 1,
             "character": "대학로 공연가와 마로니에공원 중심의 문화 거리",
             "landmarks": ["대학로", "마로니에공원", "성균관대학교"],
             "nearby_stations": ["혜화역", "종로3가역", "동대문역"],
             "nearby_dongs": ["창신동", "사직동", "청운효자동"],
             "life_area": "종로·광화문"},
            {"slug": "changsin-dong", "name": "창신동", "priority": 1,
             "character": "봉제거리와 동대문 배후 주택가가 이어진 언덕 동네",
             "landmarks": ["낙산공원", "동대문성곽", "창신동 봉제거리"],
             "nearby_stations": ["동대문역", "종로3가역", "혜화역"],
             "nearby_dongs": ["혜화동", "사직동", "삼청동"],
             "life_area": "종로·광화문"},
            {"slug": "cheongunhyoja-dong", "name": "청운효자동", "priority": 2,
             "character": "경복궁 서편 한옥과 갤러리가 모인 서촌 일대",
             "landmarks": ["경복궁", "서촌", "수성동계곡"],
             "nearby_stations": ["경복궁역", "광화문역", "안국역"],
             "nearby_dongs": ["사직동", "삼청동", "부암동"],
             "life_area": "종로·광화문"},
            {"slug": "sajik-dong", "name": "사직동", "priority": 2,
             "character": "사직단과 인왕산 자락의 조용한 도심 주거지",
             "landmarks": ["사직단", "인왕산", "경희궁"],
             "nearby_stations": ["광화문역", "경복궁역", "종각역"],
             "nearby_dongs": ["청운효자동", "삼청동", "혜화동"],
             "life_area": "종로·광화문"},
            {"slug": "samcheong-dong", "name": "삼청동", "priority": 2,
             "character": "한옥 카페거리와 갤러리가 늘어선 북촌 권역",
             "landmarks": ["북촌한옥마을", "삼청동길", "국립현대미술관"],
             "nearby_stations": ["안국역", "경복궁역", "광화문역"],
             "nearby_dongs": ["청운효자동", "사직동", "부암동"],
             "life_area": "종로·광화문"},
            {"slug": "buam-dong", "name": "부암동", "priority": 2,
             "character": "북악산 자락의 산책로와 예술 공간이 자리한 한적한 동네",
             "landmarks": ["백사실계곡", "환기미술관", "부암동 성곽길"],
             "nearby_stations": ["경복궁역", "안국역", "광화문역"],
             "nearby_dongs": ["평창동", "청운효자동", "삼청동"],
             "life_area": "종로·광화문"},
            {"slug": "pyeongchang-dong", "name": "평창동", "priority": 2,
             "character": "북한산 아래 고급 단독주택과 미술관이 모인 주거 권역",
             "landmarks": ["북한산", "평창동 갤러리", "가나아트센터"],
             "nearby_stations": ["경복궁역", "광화문역", "안국역"],
             "nearby_dongs": ["부암동", "청운효자동", "삼청동"],
             "life_area": "종로·광화문"},
        ],
    },
    {
        "slug": "jung-gu",
        "name": "중구",
        "priority": 1,
        "trait": "명동·을지로 상권과 전통시장이 밀집한 서울 도심의 한복판",
        "lead": "중구는 명동·을지로의 업무·관광 상권과 신당·약수의 주거지가 맞붙어 "
                "있는 서울 도심의 중심부입니다. 호텔과 오피스가 빽빽해 낮과 밤의 방문 "
                "수요가 크게 갈리고 이동 동선이 짧은 편입니다.",
        "stations": ["명동역", "을지로입구역", "충무로역", "동대문역사문화공원역", "신당역"],
        "life_areas": ["명동·을지로"],
        "dongs": [
            {"slug": "myeong-dong", "name": "명동", "priority": 1,
             "character": "쇼핑·관광객이 몰리는 서울 대표 상권과 호텔 밀집지",
             "landmarks": ["명동성당", "명동거리", "남산케이블카"],
             "nearby_stations": ["명동역", "을지로입구역", "충무로역"],
             "nearby_dongs": ["을지로동", "회현동", "필동"],
             "life_area": "명동·을지로"},
            {"slug": "euljiro-dong", "name": "을지로동", "priority": 1,
             "character": "인쇄·조명 골목과 노포, 오피스가 섞인 도심 업무 권역",
             "landmarks": ["을지로 골목", "세운상가", "DDP"],
             "nearby_stations": ["을지로입구역", "동대문역사문화공원역", "충무로역"],
             "nearby_dongs": ["명동", "신당동", "필동"],
             "life_area": "명동·을지로"},
            {"slug": "sindang-dong", "name": "신당동", "priority": 2,
             "character": "떡볶이타운과 중앙시장, 오래된 주거가 어우러진 동네",
             "landmarks": ["신당동 떡볶이타운", "서울중앙시장", "다산성곽길"],
             "nearby_stations": ["신당역", "동대문역사문화공원역", "약수역"],
             "nearby_dongs": ["약수동", "을지로동", "장충동"],
             "life_area": "명동·을지로"},
            {"slug": "yaksu-dong", "name": "약수동", "priority": 2,
             "character": "남산 동편 언덕의 주택가와 환승역 상권이 어우러진 생활권",
             "landmarks": ["약수역", "버티고개", "남산순환로"],
             "nearby_stations": ["약수역", "신당역", "충무로역"],
             "nearby_dongs": ["신당동", "장충동", "필동"],
             "life_area": "명동·을지로"},
            {"slug": "hoehyeon-dong", "name": "회현동", "priority": 2,
             "character": "남대문시장과 남산 자락이 맞닿은 상업·주거 혼합지",
             "landmarks": ["남대문시장", "남산공원", "회현역"],
             "nearby_stations": ["회현역", "명동역", "을지로입구역"],
             "nearby_dongs": ["명동", "필동", "을지로동"],
             "life_area": "명동·을지로"},
            {"slug": "pil-dong", "name": "필동", "priority": 2,
             "character": "남산골한옥마을과 동국대 인근의 조용한 도심 주거지",
             "landmarks": ["남산골한옥마을", "동국대학교", "충무로역"],
             "nearby_stations": ["충무로역", "명동역", "동대문역사문화공원역"],
             "nearby_dongs": ["명동", "장충동", "회현동"],
             "life_area": "명동·을지로"},
            {"slug": "jangchung-dong", "name": "장충동", "priority": 2,
             "character": "장충체육관과 족발골목, 남산 산책로가 이어지는 권역",
             "landmarks": ["장충체육관", "장충단공원", "족발골목"],
             "nearby_stations": ["동대문역사문화공원역", "약수역", "충무로역"],
             "nearby_dongs": ["필동", "약수동", "신당동"],
             "life_area": "명동·을지로"},
        ],
    },
    {
        "slug": "dongdaemun-gu",
        "name": "동대문구",
        "priority": 1,
        "trait": "청량리 광역환승과 대학가가 어우러진 동북권 관문",
        "lead": "동대문구는 청량리역 광역환승 거점과 회기·이문의 대학가, 장안·답십리의 "
                "주거지가 이어지는 서울 동북권 관문입니다. 환승 수요와 학생·직장인 "
                "거주가 섞여 시간대별로 유동 인구가 크게 달라지는 편입니다.",
        "stations": ["청량리역", "회기역", "외대앞역", "장한평역", "답십리역"],
        "life_areas": [],
        "dongs": [
            {"slug": "cheongnyangni-dong", "name": "청량리동", "priority": 2,
             "character": "광역철도 환승과 재정비가 진행되는 동북권 거점",
             "landmarks": ["청량리역", "청량리청과물시장", "롯데캐슬 SKY-L65"],
             "nearby_stations": ["청량리역", "회기역", "제기동역"],
             "nearby_dongs": ["회기동", "전농동", "휘경동"],
             "life_area": ""},
            {"slug": "hoegi-dong", "name": "회기동", "priority": 2,
             "character": "경희대·시립대 인근의 대학 상권과 자취촌이 모인 동네",
             "landmarks": ["경희대학교", "회기역", "회기동 먹자골목"],
             "nearby_stations": ["회기역", "외대앞역", "청량리역"],
             "nearby_dongs": ["휘경동", "이문동", "청량리동"],
             "life_area": ""},
            {"slug": "hwigyeong-dong", "name": "휘경동", "priority": 2,
             "character": "중랑천변 아파트 단지와 대학가 배후 주거지",
             "landmarks": ["중랑천", "휘경공원", "서울시립대학교"],
             "nearby_stations": ["외대앞역", "회기역", "청량리역"],
             "nearby_dongs": ["이문동", "회기동", "전농동"],
             "life_area": ""},
            {"slug": "imun-dong", "name": "이문동", "priority": 2,
             "character": "한국외대 인근의 대학 상권과 재개발 주택가가 섞인 동네",
             "landmarks": ["한국외국어대학교", "외대앞역", "이문동 먹자골목"],
             "nearby_stations": ["외대앞역", "회기역", "신이문역"],
             "nearby_dongs": ["휘경동", "회기동", "전농동"],
             "life_area": ""},
            {"slug": "jangan-dong", "name": "장안동", "priority": 2,
             "character": "자동차거리와 대단지 아파트가 늘어선 주거·상업지",
             "landmarks": ["장안동 자동차거리", "장한평역", "배봉산"],
             "nearby_stations": ["장한평역", "답십리역", "군자역"],
             "nearby_dongs": ["답십리동", "전농동", "휘경동"],
             "life_area": ""},
            {"slug": "jeonnong-dong", "name": "전농동", "priority": 2,
             "character": "청량리 배후의 재개발 단지와 시립대가 자리한 주거지",
             "landmarks": ["서울시립대학교", "전농동 래미안", "배봉산"],
             "nearby_stations": ["청량리역", "회기역", "답십리역"],
             "nearby_dongs": ["답십리동", "장안동", "청량리동"],
             "life_area": ""},
            {"slug": "dapsimni-dong", "name": "답십리동", "priority": 2,
             "character": "고미술상가와 아파트 단지가 어우러진 주거 권역",
             "landmarks": ["답십리고미술상가", "답십리역", "동대문중앙시장"],
             "nearby_stations": ["답십리역", "장한평역", "용두역"],
             "nearby_dongs": ["장안동", "전농동", "휘경동"],
             "life_area": ""},
        ],
    },
    {
        "slug": "jungnang-gu",
        "name": "중랑구",
        "priority": 1,
        "trait": "상봉 환승거점과 중랑천변 주거지가 이어지는 동북권 생활권",
        "lead": "중랑구는 상봉·망우의 환승 거점과 면목·묵동의 대단지 주거지가 "
                "이어지는 서울 동북권의 생활 중심지입니다. 광역버스와 철도 환승이 "
                "많아 출퇴근 동선이 뚜렷하고 정주형 주거 수요가 큰 편입니다.",
        "stations": ["상봉역", "면목역", "중화역", "먹골역", "망우역", "신내역"],
        "life_areas": ["상봉·중랑"],
        "dongs": [
            {"slug": "myeonmok-dong", "name": "면목동", "priority": 1,
             "character": "면목사거리 상권과 대단지 아파트가 밀집한 주거 중심지",
             "landmarks": ["면목역", "용마산", "면목시장"],
             "nearby_stations": ["면목역", "중화역", "상봉역"],
             "nearby_dongs": ["상봉동", "중화동", "묵동"],
             "life_area": "상봉·중랑"},
            {"slug": "sangbong-dong", "name": "상봉동", "priority": 1,
             "character": "상봉터미널과 광역환승, 복합쇼핑이 모인 동북권 관문",
             "landmarks": ["상봉역", "상봉터미널", "코스트코 상봉점"],
             "nearby_stations": ["상봉역", "망우역", "중화역"],
             "nearby_dongs": ["망우동", "중화동", "면목동"],
             "life_area": "상봉·중랑"},
            {"slug": "mangu-dong", "name": "망우동", "priority": 1,
             "character": "망우역세권과 역사공원, 주택가가 어우러진 동네",
             "landmarks": ["망우역", "망우역사문화공원", "용마폭포공원"],
             "nearby_stations": ["망우역", "상봉역", "신내역"],
             "nearby_dongs": ["상봉동", "신내동", "중화동"],
             "life_area": "상봉·중랑"},
            {"slug": "junghwa-dong", "name": "중화동", "priority": 2,
             "character": "중랑천변 주택가와 중화역 상권이 어우러진 생활권",
             "landmarks": ["중화역", "봉화산", "중랑천"],
             "nearby_stations": ["중화역", "먹골역", "상봉역"],
             "nearby_dongs": ["묵동", "면목동", "상봉동"],
             "life_area": "상봉·중랑"},
            {"slug": "muk-dong", "name": "묵동", "priority": 2,
             "character": "먹골역 인근 아파트 단지와 배 과수원으로 알려진 주거지",
             "landmarks": ["먹골역", "묵동천", "태릉"],
             "nearby_stations": ["먹골역", "중화역", "상봉역"],
             "nearby_dongs": ["중화동", "면목동", "신내동"],
             "life_area": "상봉·중랑"},
            {"slug": "sinnae-dong", "name": "신내동", "priority": 2,
             "character": "신내차량기지와 택지지구 대단지가 자리한 정주 권역",
             "landmarks": ["신내역", "봉화산", "신내차량기지"],
             "nearby_stations": ["신내역", "망우역", "먹골역"],
             "nearby_dongs": ["망우동", "묵동", "중화동"],
             "life_area": "상봉·중랑"},
        ],
    },
]
