# -*- coding: utf-8 -*-
"""구구 마사지 — 서울 지하철역별 안내 데이터.

각 역(STATIONS) 딕셔너리 스키마:
    slug, name, priority, lines, nearby_dongs, nearby_gu, life_area, character
"""

STATIONS = [
    {
        "slug": "gangnam-station",
        "name": "강남역",
        "priority": 1,
        "lines": ["2호선", "신분당선"],
        "nearby_dongs": ["역삼동", "서초동", "논현동"],
        "nearby_gu": ["강남구", "서초구"],
        "life_area": "강남·역삼",
        "character": "서울 최대 유동인구의 업무·상권 중심지",
    },
    {
        "slug": "yeoksam-station",
        "name": "역삼역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["역삼동", "논현동"],
        "nearby_gu": ["강남구"],
        "life_area": "강남·역삼",
        "character": "오피스 빌딩이 밀집한 직장인 업무지구",
    },
    {
        "slug": "seolleung-station",
        "name": "선릉역",
        "priority": 1,
        "lines": ["2호선", "수인분당선"],
        "nearby_dongs": ["삼성동", "역삼동", "대치동"],
        "nearby_gu": ["강남구"],
        "life_area": "삼성·선릉",
        "character": "테헤란로 IT·벤처 기업 밀집 업무지",
    },
    {
        "slug": "samseong-station",
        "name": "삼성역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["삼성동", "대치동"],
        "nearby_gu": ["강남구"],
        "life_area": "삼성·선릉",
        "character": "코엑스·무역센터 전시·컨벤션 중심지",
    },
    {
        "slug": "jamsil-station",
        "name": "잠실역",
        "priority": 1,
        "lines": ["2호선", "8호선"],
        "nearby_dongs": ["잠실동", "신천동"],
        "nearby_gu": ["송파구"],
        "life_area": "잠실·송파",
        "character": "롯데월드타워·대형 상업시설 환승 거점",
    },
    {
        "slug": "seokchon-station",
        "name": "석촌역",
        "priority": 1,
        "lines": ["8호선", "9호선"],
        "nearby_dongs": ["석촌동", "송파동", "삼전동"],
        "nearby_gu": ["송파구"],
        "life_area": "잠실·송파",
        "character": "석촌호수 인근 주거·생활 상권",
    },
    {
        "slug": "munjeong-station",
        "name": "문정역",
        "priority": 1,
        "lines": ["8호선"],
        "nearby_dongs": ["문정동", "장지동", "가락동"],
        "nearby_gu": ["송파구"],
        "life_area": "문정·가락",
        "character": "법조타운·지식산업센터 신흥 업무지",
    },
    {
        "slug": "hongik-univ-station",
        "name": "홍대입구역",
        "priority": 1,
        "lines": ["2호선", "경의중앙선", "공항철도"],
        "nearby_dongs": ["서교동", "동교동", "연남동"],
        "nearby_gu": ["마포구"],
        "life_area": "홍대·합정",
        "character": "젊음의 거리·클럽·카페 밀집 대학 상권",
    },
    {
        "slug": "hapjeong-station",
        "name": "합정역",
        "priority": 1,
        "lines": ["2호선", "6호선"],
        "nearby_dongs": ["합정동", "서교동", "망원동"],
        "nearby_gu": ["마포구"],
        "life_area": "홍대·합정",
        "character": "한강변 카페·복합쇼핑몰 환승 상권",
    },
    {
        "slug": "gongdeok-station",
        "name": "공덕역",
        "priority": 1,
        "lines": ["5호선", "6호선", "경의중앙선", "공항철도"],
        "nearby_dongs": ["공덕동", "신공덕동", "도화동"],
        "nearby_gu": ["마포구"],
        "life_area": "공덕·마포",
        "character": "4개 노선이 교차하는 주요 환승 업무지",
    },
    {
        "slug": "yeouido-station",
        "name": "여의도역",
        "priority": 1,
        "lines": ["5호선", "9호선"],
        "nearby_dongs": ["여의동"],
        "nearby_gu": ["영등포구"],
        "life_area": "여의도·영등포",
        "character": "증권·금융사 본사가 모인 금융 중심지",
    },
    {
        "slug": "yeongdeungpo-station",
        "name": "영등포역",
        "priority": 1,
        "lines": ["1호선"],
        "nearby_dongs": ["영등포동", "영등포본동"],
        "nearby_gu": ["영등포구"],
        "life_area": "여의도·영등포",
        "character": "백화점·전통시장이 공존하는 도심 상권",
    },
    {
        "slug": "dangsan-station",
        "name": "당산역",
        "priority": 1,
        "lines": ["2호선", "9호선"],
        "nearby_dongs": ["당산동", "양평동"],
        "nearby_gu": ["영등포구"],
        "life_area": "문래·당산",
        "character": "한강 다리 연결 주거·교통 환승 거점",
    },
    {
        "slug": "sillim-station",
        "name": "신림역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["신림동", "신원동"],
        "nearby_gu": ["관악구"],
        "life_area": "신림·관악",
        "character": "고시촌·먹자골목 청년층 밀집 상권",
    },
    {
        "slug": "seoul-natl-univ-station",
        "name": "서울대입구역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["봉천동", "청룡동", "은천동"],
        "nearby_gu": ["관악구"],
        "life_area": "서울대입구·봉천",
        "character": "대학가 인근 1인 가구 주거·상권",
    },
    {
        "slug": "kondae-station",
        "name": "건대입구역",
        "priority": 1,
        "lines": ["2호선", "7호선"],
        "nearby_dongs": ["화양동", "자양동"],
        "nearby_gu": ["광진구"],
        "life_area": "건대·광진",
        "character": "건국대 인근 먹자골목·번화한 대학 상권",
    },
    {
        "slug": "guui-station",
        "name": "구의역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["구의동", "자양동"],
        "nearby_gu": ["광진구"],
        "life_area": "건대·광진",
        "character": "주거단지와 강변 인접 생활 상권",
    },
    {
        "slug": "wangsimni-station",
        "name": "왕십리역",
        "priority": 1,
        "lines": ["2호선", "5호선", "경의중앙선", "수인분당선"],
        "nearby_dongs": ["행당동", "도선동", "상왕십리동"],
        "nearby_gu": ["성동구"],
        "life_area": "성수·왕십리",
        "character": "민자역사·다중 노선이 모인 환승 허브",
    },
    {
        "slug": "seongsu-station",
        "name": "성수역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["성수동1가", "성수동2가"],
        "nearby_gu": ["성동구"],
        "life_area": "성수·왕십리",
        "character": "공장 개조 카페·팝업이 모인 핫플레이스",
    },
    {
        "slug": "seoulsup-station",
        "name": "서울숲역",
        "priority": 1,
        "lines": ["수인분당선"],
        "nearby_dongs": ["성수동1가", "성수동2가"],
        "nearby_gu": ["성동구"],
        "life_area": "성수·왕십리",
        "character": "서울숲 공원 인접 신흥 주거·문화지",
    },
    {
        "slug": "yongsan-station",
        "name": "용산역",
        "priority": 1,
        "lines": ["1호선", "경의중앙선"],
        "nearby_dongs": ["한강로동", "이촌동"],
        "nearby_gu": ["용산구"],
        "life_area": "용산·서울역",
        "character": "전자상가·복합쇼핑몰·KTX 교통 거점",
    },
    {
        "slug": "seoul-station",
        "name": "서울역",
        "priority": 1,
        "lines": ["1호선", "4호선", "경의중앙선", "공항철도"],
        "nearby_dongs": ["남영동", "회현동", "후암동"],
        "nearby_gu": ["용산구", "중구"],
        "life_area": "용산·서울역",
        "character": "KTX·공항철도가 모인 국가 관문 역",
    },
    {
        "slug": "itaewon-station",
        "name": "이태원역",
        "priority": 1,
        "lines": ["6호선"],
        "nearby_dongs": ["이태원동", "한남동"],
        "nearby_gu": ["용산구"],
        "life_area": "한남·이태원",
        "character": "외국인·다국적 음식 거리의 관광 상권",
    },
    {
        "slug": "hangangjin-station",
        "name": "한강진역",
        "priority": 1,
        "lines": ["6호선"],
        "nearby_dongs": ["한남동", "이태원동"],
        "nearby_gu": ["용산구"],
        "life_area": "한남·이태원",
        "character": "고급 주택가·갤러리가 자리한 한남동 일대",
    },
    {
        "slug": "sadang-station",
        "name": "사당역",
        "priority": 1,
        "lines": ["2호선", "4호선"],
        "nearby_dongs": ["사당동", "방배동"],
        "nearby_gu": ["동작구", "서초구"],
        "life_area": "",
        "character": "경기 남부 광역버스 환승 교통 요지",
    },
    {
        "slug": "noryangjin-station",
        "name": "노량진역",
        "priority": 1,
        "lines": ["1호선", "9호선"],
        "nearby_dongs": ["노량진동", "대방동"],
        "nearby_gu": ["동작구"],
        "life_area": "",
        "character": "공무원 학원가·수산시장으로 유명한 지역",
    },
    {
        "slug": "guro-digital-complex-station",
        "name": "구로디지털단지역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["구로동"],
        "nearby_gu": ["구로구"],
        "life_area": "구디·가디",
        "character": "IT 벤처·지식산업센터 직장인 밀집지",
    },
    {
        "slug": "gasan-digital-complex-station",
        "name": "가산디지털단지역",
        "priority": 1,
        "lines": ["1호선", "7호선"],
        "nearby_dongs": ["가산동"],
        "nearby_gu": ["금천구"],
        "life_area": "구디·가디",
        "character": "패션 아울렛·디지털단지 업무 상권",
    },
    {
        "slug": "sindorim-station",
        "name": "신도림역",
        "priority": 1,
        "lines": ["1호선", "2호선"],
        "nearby_dongs": ["신도림동", "구로동"],
        "nearby_gu": ["구로구"],
        "life_area": "",
        "character": "1·2호선 대규모 환승과 복합몰 거점",
    },
    {
        "slug": "express-bus-terminal-station",
        "name": "고속터미널역",
        "priority": 1,
        "lines": ["3호선", "7호선", "9호선"],
        "nearby_dongs": ["반포동", "잠원동"],
        "nearby_gu": ["서초구"],
        "life_area": "",
        "character": "고속버스터미널·지하상가 교통 요지",
    },
    {
        "slug": "seoul-natl-univ-of-education-station",
        "name": "교대역",
        "priority": 1,
        "lines": ["2호선", "3호선"],
        "nearby_dongs": ["서초동"],
        "nearby_gu": ["서초구"],
        "life_area": "",
        "character": "법원·검찰청 인접 업무·환승 지역",
    },
    {
        "slug": "yangjae-station",
        "name": "양재역",
        "priority": 1,
        "lines": ["3호선", "신분당선"],
        "nearby_dongs": ["양재동", "서초동"],
        "nearby_gu": ["서초구"],
        "life_area": "",
        "character": "강남권 진입로·기업 본사 인접 업무지",
    },
    {
        "slug": "magok-station",
        "name": "마곡역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["마곡동", "방화동"],
        "nearby_gu": ["강서구"],
        "life_area": "",
        "character": "대기업 R&D 단지가 들어선 신도시",
    },
    {
        "slug": "balsan-station",
        "name": "발산역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["우장산동", "내발산동"],
        "nearby_gu": ["강서구"],
        "life_area": "",
        "character": "마곡 인접 주거단지·생활 상권",
    },
    {
        "slug": "hwagok-station",
        "name": "화곡역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["화곡동"],
        "nearby_gu": ["강서구"],
        "life_area": "",
        "character": "다세대 주택이 밀집한 대규모 주거지",
    },
    {
        "slug": "mokdong-station",
        "name": "목동역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["목동", "신정동"],
        "nearby_gu": ["양천구"],
        "life_area": "목동·양천",
        "character": "학원가와 아파트가 모인 교육 주거지",
    },
    {
        "slug": "omokgyo-station",
        "name": "오목교역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["목동", "신정동"],
        "nearby_gu": ["양천구"],
        "life_area": "목동·양천",
        "character": "목동 백화점·방송사 인접 생활 상권",
    },
    {
        "slug": "yeonsinnae-station",
        "name": "연신내역",
        "priority": 1,
        "lines": ["3호선", "6호선"],
        "nearby_dongs": ["불광동", "갈현동"],
        "nearby_gu": ["은평구"],
        "life_area": "연신내·은평",
        "character": "은평구 대표 번화가·환승 상권",
    },
    {
        "slug": "bulgwang-station",
        "name": "불광역",
        "priority": 1,
        "lines": ["3호선", "6호선"],
        "nearby_dongs": ["불광동", "대조동"],
        "nearby_gu": ["은평구"],
        "life_area": "연신내·은평",
        "character": "주거지와 관공서가 모인 생활 거점",
    },
    {
        "slug": "nowon-station",
        "name": "노원역",
        "priority": 1,
        "lines": ["4호선", "7호선"],
        "nearby_dongs": ["상계동", "중계동"],
        "nearby_gu": ["노원구"],
        "life_area": "노원·상계",
        "character": "대규모 아파트 단지·학원가 주거 상권",
    },
    {
        "slug": "sangbong-station",
        "name": "상봉역",
        "priority": 1,
        "lines": ["7호선", "경의중앙선", "경춘선"],
        "nearby_dongs": ["상봉동", "망우동", "면목동"],
        "nearby_gu": ["중랑구"],
        "life_area": "상봉·중랑",
        "character": "터미널·복합환승센터 동북부 교통지",
    },
    {
        "slug": "jongno-3ga-station",
        "name": "종로3가역",
        "priority": 1,
        "lines": ["1호선", "3호선", "5호선"],
        "nearby_dongs": ["종로1·2·3·4가동", "익선동"],
        "nearby_gu": ["종로구"],
        "life_area": "종로·광화문",
        "character": "익선동 한옥·귀금속 거리의 도심 상권",
    },
    {
        "slug": "gwanghwamun-station",
        "name": "광화문역",
        "priority": 1,
        "lines": ["5호선"],
        "nearby_dongs": ["사직동", "청운효자동"],
        "nearby_gu": ["종로구"],
        "life_area": "종로·광화문",
        "character": "정부청사·대기업 본사 도심 업무지",
    },
    {
        "slug": "myeongdong-station",
        "name": "명동역",
        "priority": 1,
        "lines": ["4호선"],
        "nearby_dongs": ["명동", "회현동"],
        "nearby_gu": ["중구"],
        "life_area": "명동·을지로",
        "character": "외국인 관광·쇼핑·호텔 밀집 상권",
    },
    {
        "slug": "euljiro-ipgu-station",
        "name": "을지로입구역",
        "priority": 1,
        "lines": ["2호선"],
        "nearby_dongs": ["을지로동", "명동"],
        "nearby_gu": ["중구"],
        "life_area": "명동·을지로",
        "character": "은행 본점·노포 골목이 공존하는 업무지",
    },
    {
        "slug": "dongdaemun-history-culture-park-station",
        "name": "동대문역사문화공원역",
        "priority": 1,
        "lines": ["2호선", "4호선", "5호선"],
        "nearby_dongs": ["을지로동", "광희동", "신당동"],
        "nearby_gu": ["중구"],
        "life_area": "명동·을지로",
        "character": "DDP·의류도매 상가 인접 환승 거점",
    },
]
